### ISSUE TITLE
Create Dev server

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#1]
We need a dev server to test and review developments for the Nexus Platform,
A basic setup is ok:

 - Ubuntu 20.04
 - Docker + Docker Compose (for the GeoNode stack)

DNS: `dev.nexus.geo-solutions.it`

**Comment by randomorder** [comment]
please subit a request [here](https://github.com/geosolutions-it/DevOps/issues/new/choose)

**Comment by giohappy** [comment]
@randomorder [done](https://github.com/geosolutions-it/DevOps/issues/464)

**Comment by giohappy** [comment]
docs are [here](https://docs.google.com/document/d/1P0M94t6QWqvngp0KqTY44KshQbRIUwMjbqb5OwTtiS4/)
