### ISSUE TITLE
Client - Overflow of text in cards list shows horizontal scrollbar

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#109]
Steps:
- go to root path #/
- select cards as list and ensure to have a resource with long title
- shrink the screen width

_Expected result:_

- text overflow ellipsis
- no horizontal scrollbar

![image](https://user-images.githubusercontent.com/19175505/117311217-4b77f180-ae84-11eb-8361-09ca46c4d527.png)

_Current result:_

- text all visible
- horizontal scrollbar
- not aligned image size

![image](https://user-images.githubusercontent.com/19175505/117310284-69912200-ae83-11eb-99e1-c3ec0c513273.png)

**Comment by giohappy** [comment]
Card still has some overflow

![image](https://user-images.githubusercontent.com/571129/118113715-eaea3680-b3e6-11eb-9223-9a73b7d25c4a.png)

**Comment by luorlandini** [comment]
@giohappy Does that issue happen, in a specific behavior or browser?

I checked on chrome and FF, the text overflow ellipsis seems to work 


![Schermata 2021-05-14 alle 10 28 09](https://user-images.githubusercontent.com/4085786/118244581-fc434980-b49f-11eb-8ccd-fda78f2589c5.png)

![Schermata 2021-05-14 alle 10 27 41](https://user-images.githubusercontent.com/4085786/118244371-c00fe900-b49f-11eb-8c90-8977f555307b.png)
