### ISSUE TITLE
Mapstore refactor API v2: migrate blob to new table

### ISSUE THREAD

**Issue by mattiagiupponi** [geosolutions-it/nexus-geonode#123]
With the development made in the epic, now the data blob are stored in `map_data` instead of `mapstore2_adapter_mapstoreresource`.
Is required to have a migration file in order to move all the blob files into the new table and assign them to the correct resource

**Comment by mattiagiupponi** [comment]
@giohappy for this migration we will have 2 choices:
1. Maintain the models in order to use the Django `ORM `to migrate the values from the old table to the new one and find a way to deprecated them (maybe override the save method and show in some way a warning). This migration will use [RunPython](https://docs.djangoproject.com/en/3.2/ref/migration-operations/#runpython)
2. Delete the models from the MapStore library and use the `SQL` to run the migration ([RunSQL](https://docs.djangoproject.com/en/3.2/ref/migration-operations/#runsql))

I prefer the second one since we will delete the models and they will not be available anymore, but this can create some issue with the retro-compability

Any thoughts?

**Comment by giohappy** [comment]
What about two migrations in sequence where the first one migrates the data and the second one removes the models? If they're `managed` they should be automatically deleted from DB too.

**Comment by mattiagiupponi** [comment]
> What about two migrations in sequence where the first one migrates the data and the second one removes the models? If they're `managed` they should be automatically deleted from DB too.
Yes, this is exactly what I did here:
First migration into `maps`  -> https://github.com/GeoNode/geonode/blob/16bc3f13a430cea16657892873d0d549426a5ba9/geonode/maps/migrations/0033_map_blob_migration.py
Second migration into mapstore -> https://github.com/GeoNode/geonode-mapstore-client/blob/1b9bb6469acbc79df5f9f1d51bd5ce33290f76d8/mapstore2_adapter/migrations/0005_remoe_mastore_models.py

by `models` in this comment, I mean the file `models.py`. If we want to approach the migration with the Django ORM, we cannot delete the file
