### ISSUE TITLE
[Storage Manager] Django Cloud Storage API based implementation based on "django-storages"

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/nexus-geonode#126]

**Comment by mattiagiupponi** [comment]
Here some results based on the Tests with `dropbox`:
Settings used:
```python
STORAGE_MANAGER_CONCRETE_CLASS = 'storages.backends.dropbox.DropBoxStorage'
DEFAULT_FILE_STORAGE = "storages.backends.dropbox.DropBoxStorage"
DROPBOX_OAUTH2_TOKEN = CONNECTION_TOKEN
```

From console:
```shell
In [6]: from geonode.storage.manager import StorageManager
In [6]: drx = StorageManager()

In [6]: drx.listdir('Apps/')
Out[6]: (['geonode-storage'], [])
```

Some commands are already mapped by the `StorageManager`, while some commands are not defined by `storages.backends.dropbox.DropBoxStorage` (ex: save)
To upload the file to the storages, it looks like that is required to create a field in the model like: 
```python
file = models.FileField(upload_to=some_path)
```
and not directly from the object. `DropBoxStorage` use a `_save()` method. we can remap also this method and use the one required

**Comment by afabiani** [comment]
@mattiagiupponi we need a common interface for any pluggable storage manager, so let's see how difficult/if it is possible to remap the methods to the interface or otherwise let's envisage some changes to the conceptual model.

**Comment by mattiagiupponi** [comment]
@afabiani here is a PR with some basic implementation of 3 storages `Dropbox`, `gcs` and `aws`: https://github.com/geosolutions-it/geonode/pull/776

Just wrap the API method from `django-storages` library.
Of course for some settings, is required to follow this doc https://django-storages.readthedocs.io/en/latest/index.html
