### ISSUE TITLE
Merge mapstore client and django adapter modules

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#14]
The initial idea was to have a module that could host the adapters between the mapstore client and django apps implementations, including geonode. By the way the only application that has been implemented is geonode, and the abstract / generic architecture of the adapter has been predated by the geonode specific adapter. 

I don't see any valid reason to keep the masptore client and the adapter module separated now. @afabiani what's your opinion on this? If there isn't a valid reason let's merge the two into the masptore client module.

**Comment by afabiani** [comment]
@giohappy please review this PR [here](https://github.com/GeoNode/geonode-mapstore-client/pull/80).

This is currently the less-impacting merge possible and does not require any action to update the models and/or already existing tables.

Moving everything into one application requires to rebuild completely the model.
