### ISSUE TITLE
Client - Extent filter renders only one bbox when it crosses the IDL

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#149]
steps to reproduce:

- enable filters in #/search/ page
- enable filter by extent
- move the map to cross the international date line

_Expected Result_:

- the filter should display the full extent of the selected bbox even if it crosses the IDL

_Current Result_:

- there is only half bbox rendered in the filter preview

![image](https://user-images.githubusercontent.com/19175505/118151526-0455a780-b414-11eb-89d7-27d459dc4dda.png)

**Comment by MuhweziDeo** [comment]
Hey @giohappy In the fix to make this work as expected we will have two bounding boxes drawn when the extent crosses the international date line as shown in the screenshot below. Maybe reducing the stroke width may help a bit but the intersection might still be visible to the user.
<img width="370" alt="Screenshot 2021-05-20 at 13 49 54" src="https://user-images.githubusercontent.com/39124174/118967066-ea1b4c80-b972-11eb-9af2-9ced34fd7e59.png">

**Comment by giohappy** [comment]
@MuhweziDeo let's try removing the stroke. 
In case we will change a bit the opacity or the hue of the overlay to make it more evident.

Please when fixing keep into account the strange behaviours shown in the video, like extent and zoom moving in unexpected ways.

**Comment by allyoucanmap** [comment]
> Please when fixing keep into account the strange behaviours shown in the video, like extent and zoom moving in unexpected ways.

@giohappy I don't know how much we can control the zooming due the fact we are using .fit of openlayers.

@MuhweziDeo  please take a look to the OpenLayers options related to view .fit function and see if we can use some options to mitigate this camera zooming, maybe the nearest property?

https://openlayers.org/en/latest/apidoc/module-ol_View-View.html#fit

**Comment by giohappy** [comment]
Do we need to make a fit? My expectation is that when the filter is set it simply updates the bbox without doing any action on the positioning of the map.

**Comment by allyoucanmap** [comment]
> Do we need to make a fit? My expectation is that when the filter is set it simply updates the bbox without doing any action on the positioning of the map.

yes, probably we could avoid fit when the panel is open, I think it's needed only when the component is mounted
