### ISSUE TITLE
Activate the new home page

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#15]
@allyoucanmap for the purpose of showing the initial work done for the new home page we want to activate it here.
It should only be a matter of setting the right js bundles inside the index template, right?

**Comment by allyoucanmap** [comment]
@giohappy we need to override the index.html of geonode via geonode-project with the content of [home.html](https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/client/home.html) template

**Comment by giohappy** [comment]
you can proceed @allyoucanmap

**Comment by allyoucanmap** [comment]
@giohappy here the PR https://github.com/geosolutions-it/nexus-geonode/pull/16
