### ISSUE TITLE
[Harvesting] Implement abstract interfaces and logic for resources retrieval

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#172]
We need to following key operations to be implemented. Some might depend on the client capabilities (i.e. what can be supported depending on the type of remote source).

 - Retrieve the list of remote sources, potentially with a filter to limit resources (filtering caps depend on the client)
 - Select the resources to be harvested, either as a list of resources or through a filter (filtering caps depend on the client). This will replace and extend what we have know for remote services, where the user is given the option to select the resources to be imported.
 - Retrieve the metadata for the selected resources. The basic information will be name / title
 - Store the remote resource information (see #181)
 - Request the update of the remote resources metadata (trigger a new harvest, either interactively or through scheduling). In case a remote resource is not available anymore it should be marked somehow:
    - if it's a metadata only resource, the UI will notify the user that the online resource service is not available anymore, and so the viewer won't be able to show the resource.
    - if we also have harvested the remote resource data we will notify that the original remote resource is not available anymore.

**Comment by ricardogsilva** [comment]
I've drawn a couple of diagrams to depict the high level overview of what I am implementing:

![select-harvestable-resources](https://user-images.githubusercontent.com/732010/118794044-18c0f680-b891-11eb-858f-61ead0f34664.png)

**Comment by ricardogsilva** [comment]
![remote-resource-added](https://user-images.githubusercontent.com/732010/118794403-73f2e900-b891-11eb-99e9-503a6118d805.png)

**Comment by ricardogsilva** [comment]
![remote-resource-deleted](https://user-images.githubusercontent.com/732010/118794440-7e14e780-b891-11eb-8568-9c28a509f180.png)

**Comment by ricardogsilva** [comment]
![harvester-deleted](https://user-images.githubusercontent.com/732010/118794483-8705b900-b891-11eb-9558-50e3ee9b2baa.png)
