### ISSUE TITLE
[Upload / Import refactoring] Get rid of "geoserver.rest" mode and sync uploads

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/nexus-geonode#174]
As a general rule -> Code cleanup and readability as much as possible:
 1. Let's remove completely any setting, methods, classes, code snippets and function that are not going to be used anymore
 2. Let's avoid huge methods, eventually split them into utility function
 3. Code reuse as much as possible; avoid to spread utility function around the modules without a logic.

- [x] Remove the possibility to enable the "geoserver.rest" modality
- [x] Remove the synchronous "file_upload" methods
- [x] Refactor the "Replace Layer"
- [x] Refactor the "Style Upload"
- [x] Refactor the "Metadata Upload"
- [x] Review the "Append Data"
- [x] Refactor the "updatelayers" management command
- [x] Refactor the "importlayers" management command
- [x] Cleanup any reference to that sync mode
- [x] Fix the tests (remove the outdated ones, adapt the ones using "file_upload")
- [x] Fix the documentation (if needed)

**Comment by mattiagiupponi** [comment]
- [ ] Remove the possibility to enable the "geoserver.rest" modality
- [ ] Remove the synchronous "file_upload" methods
- [x] Refactor the "Replace Layer" | in progress
- [ ] Refactor the "Style Upload"
- [ ] Refactor the "Metadata Upload"
- [x] Review the "Append Data" | in progress 
- [ ] Refactor the "updatelayers" management command
- [ ] Refactor the "importlayers" management command
- [ ] Cleanup any reference to that sync mode
- [ ] Fix the tests (remove the outdated ones, adapt the ones using "file_upload") | in progress
- [ ] Fix the documentation (if needed)

**Comment by mattiagiupponi** [comment]
The doc is available in this branch. -> https://github.com/GeoNode/documentation/tree/importlayers_upload
Do i need to open the PR to master (for the doc)?

**Comment by afabiani** [comment]
@mattiagiupponi yes please

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi yes please

https://github.com/GeoNode/documentation/pull/102
