### ISSUE TITLE
[Harvesting - GeoNode Client] Design client model, operations and configurable options

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#175]
The client will support:

- filtering of remote resources to be **listed** (title, time window, categories, keywords)
- selection of remote resources to be **harvested** (list of names or filtering by title, time window, categories, keywords
- configure the client instance either to retrieve only metadata or also data
- check and retrieve updates for already for previously harvested resources (based on update date on remote resource metadata)
- implement general helth check on remote service

**Comment by ricardogsilva** [comment]
I have already done part of the work described in this issue with the PR in geonode/geonode#7317.

- [ ] **Filtering of remote resources to be listed (title, time window, categories, keywords)** - There is some support for this in the PR. This has been introduced at the level of each harvester type - the GeoNode harvester type is able to offer these filters. But the WMS harvester will likely not have them. I will need to fesh this out, but the base is there

- [ ] **Selection of remote resources to be harvested (list of names or filtering by title, time window, categories, keywords** - The current PR does not provide the means to get a list of existing remote resources yet, but that is a small addition - I have the code that does that internally already, it is just not being exposed. I will need to add an additional model to the DB to track which resources are being managed by each harvester

- [ ] **Configure the client instance either to retrieve only metadata or also data** - I have not started working on the actual data retrieval yet, but in terms of just the configuration this shall be a small addition to the work in the PR

- [ ] **Check and retrieve updates for already for previously harvested resources (based on update date on remote resource metadata)** - I have also not started working on this yet.  

- [ ] implement general health check on remote service - I have implemented support for this in the PR
