### ISSUE TITLE
[Harvesting - GeoNode Client] Harvesting of layers data

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#178]

**Comment by ricardogsilva** [comment]
@meomancer There is some degree of support for this already merged in geonode/geonode#7843 - The `harvesting.harvesters.base.download_resource_file` should be able to download the remote layer from its remote url.

Moreover, `harvesting.harvester.geonode.GeoNodeLegacyHarvester.get_distribution_info()` should be able to return a URL for a downloadable resource in its response - look for the `RecordDistribution.original_format_url` field.

We need to add a `copy_layers` option to the harvester, similarly to the already existing `copy_documents`, which the user can set to `true` when he wishes to have remote layers be copied locally - this shall default to `false`.

Then we need to make sure the geonode resource manager is able to correctly create a GeoNode resource from the downloaded layer. Please speak with @afabiani if you have some doubts about the implementation of this.

**Comment by giohappy** [comment]
can this be closed @ricardogsilva?

**Comment by ricardogsilva** [comment]
@giohappy Yes, the GeoNode harvester that was merged upstream is able to copy both metadata and data, if appropriately configured. So we can close this - closing
