### ISSUE TITLE
[Harvesting - Scheduling] Implement scheduler API

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#188]

**Comment by ricardogsilva** [comment]
My PR geonode/geonode#7317 already includes support for configuring some harvesting-related parameters via the harvester's REST API. I need to enhance this with some more config-related stuff, but the basic skeleton is there.

I plan to keep the scheduler private. Users will interact with harvesters (via the REST API or the django-admin) and harvesters will speak to the scheduler in a way that is opaque to the user.

**Comment by ricardogsilva** [comment]
Harvesting via API is already implemented in GeoNode. Clients do not interact with the scheduler directly, but rather manipulate the `status` of a harvester by submitting `HTTP PATCH` requests to `harvesters/{harvester-id}`.

We can close this
