### ISSUE TITLE
[Harvesting] - Model scheduler configuration

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#189]

**Comment by ricardogsilva** [comment]
I have already done most of the work related to this issue. It is present on geonode/geonode#7317

As commented on #187 django-celery-beat provides the `PerdiodicTask`, which is able to store task execution parameters. While using this directly could be useful for other GeoNode-related functionality, for the harvesting I have decided to use the `harvesting.models.Harvester` model. This harvester model has a 1:1 relationship with the periodic task model and it keeps harvesting-related configuration in a single place. This makes it easier to interact with the harvesters when using the django-admin.

**Comment by ricardogsilva** [comment]
We can close this, since the work mentioned in my previous comment has now been merged to GeoNode master branch
