### ISSUE TITLE
[Upload / Import refactoring] Allow the Documents to store FILES through the StorageManager

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/nexus-geonode#192]
- [x] Refactor the `Document` upload by removing the `FileField` and make use of `ResourceBase.FIELS`
- [x] Allow the `Documents` to R/W data from the `StorageManager`

**Comment by mattiagiupponi** [comment]
|Task|Status|
|---|---|
|Refactor the `Document` upload by removing the `FileField` and make use of `ResourceBase.FIELS` | **in progress** |
|Allow the `Documents` to R/W data from the `StorageManager` |  **in progress** |
