### ISSUE TITLE
API v2 favorites

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#195]
- `/resources/favorites` GET return the list of favorite resources for the user
-  `/resources/favorites/{resource_pk}`: POST / DELETE to add / remove a resource the user's favorites
- a new boolean `favorite` property inside resources (list and detail) will return if the resource is a favorite for the authenticated user.

**Comment by marthamareal** [comment]
@giohappy  i suggest we have this api in this format since it will be under ResourcBase view
`/resources/{resource_pk}/favorite`: POST / DELETE to add / remove a resource the user's favorites.
