### ISSUE TITLE
[Upload / Import refactoring] Make the Upload to store FILES through the StorageManager

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/nexus-geonode#197]
- [x] Initialize the `StorageManager` at [`__init`](https://github.com/geosolutions-it/geonode/blob/nexus_master/geonode/storage/__init__.py) time
- [x] Adapt the [`UploadFile`](https://github.com/geosolutions-it/geonode/blob/nexus_master/geonode/upload/models.py#L328) class accordingly by storing the name/path of the files only
- [x] Make the `UploadFile` class being able to rely on the `StorageManager`
- [x] Make the `Upload` class being able to [store the files](https://github.com/geosolutions-it/geonode/blob/nexus_master/geonode/upload/models.py#L114) through the `StorageManager`

**Comment by mattiagiupponi** [comment]
|Task|Status|
|---|---|
| Initialize the `StorageManager` at [`__init`](https://github.com/geosolutions-it/geonode/blob/nexus_master/geonode/storage/__init__.py) time | **in progress**  |
| Adapt the [`UploadFile`](https://github.com/geosolutions-it/geonode/blob/nexus_master/geonode/upload/models.py#L328) class accordingly by storing the name/path of the files only |   |
| Make the `UploadFile` class being able to rely on the `StorageManager` |  | 
|  Make the `Upload` class being able to [store the files](https://github.com/geosolutions-it/geonode/blob/nexus_master/geonode/upload/models.py#L114) through the `StorageManager` |  |
| QA |   |

**Comment by mattiagiupponi** [comment]
|Task|Status|
|---|---|
| Test coverage | **in progress**  |
