### ISSUE TITLE
[Upload / Import refactoring] Make the proxy and proxy_tag to fetch the FILES through the StorageManager

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/nexus-geonode#198]
Depends on: https://github.com/geosolutions-it/nexus-geonode/issues/197

- [x] `proxy_lib_tgs` [here](https://github.com/geosolutions-it/geonode/blob/nexus_master/geonode/proxy/templatetags/proxy_lib_tags.py#L59)
- [x] `proxy views` [here](https://github.com/geosolutions-it/geonode/blob/nexus_master/geonode/proxy/views.py#L283)

**Comment by mattiagiupponi** [comment]
|Task|Status|
|---|---|
| proxy_lib_tgs  | **Done**  |
| proxy views | **Done**  |
| QA | **Done**  |
| Test coverage | **in progress**  |
