### ISSUE TITLE
Implement filter backend for favorites

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#205]
Favorites have been implemented as a [paginator + custom serializer](https://github.com/GeoNode/geonode/blob/master/geonode/base/api/views.py#L266). This is ok in general but [it doesn't support mixing favorites with other resource fitlers](https://github.com/geosolutions-it/nexus-geonode/issues/165#issuecomment-850277778). 

I propose to add a FavoritesFilter [backend](https://github.com/GeoNode/geonode/blob/master/geonode/base/api/views.py#L229) for `favorites`, similar to what we already do with the ExtentFilter.

**Comment by mattiagiupponi** [comment]
https://github.com/GeoNode/geonode/pull/7627
