### ISSUE TITLE
Display number of active filters

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#210]
After playing a bit with the filters (and seeing what others do) having the number of active filters shown is a helpful hint.
@lpasquali was already setting it, then we decided to show the number of filtered resources. I would show both instead

![image](https://user-images.githubusercontent.com/571129/121327261-936eb600-c913-11eb-8534-b0429fda4a2a.png)

**Comment by luorlandini** [comment]
@giohappy  when no filter is set, do we show Filters (0), right? Like resources found label

**Comment by giohappy** [comment]
@luorlandini no, we simply don't show the parenthesis. Like in Amazon:

Filters set
![image](https://user-images.githubusercontent.com/571129/121553151-538df880-ca11-11eb-9336-bcd074b17b11.png)

Filters not set
![image](https://user-images.githubusercontent.com/571129/121553172-58eb4300-ca11-11eb-8f21-09e60158aab7.png)

**Comment by luorlandini** [comment]
@giohappy ok
