### ISSUE TITLE
Refactor resource types filter to a filters tree

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#211]
We want to support subfilter (Vector dataset, Raster dataser, Vector Time series, etc.), so the current approach of selecting single types doesn't scale.

The ides is to remove the "resource types" selection and change it to a filter tree to be put under the "Resources" filters block.
For the moment the list of filters will be hardcoded, instead of using the resource types returned from the API.
This filters will be available also to anonymous users.

In the end we will obtain something like this:

**Resources**
- [ ] My resources
- [ ] Pending approval
 - [ ] Datasets (with caret to expand / collapse subfilters)
   - [ ] Vector
   - [ ] Time Series
   - [ ] Raster
   - [ ] Remote
- [ ] Documents
- [ ] Maps
- [ ] Geostories

**Comment by luorlandini** [comment]
@giohappy about Datasets, will It be only a toggle to expand / collapse subfilters?

**Comment by giohappy** [comment]
where we are with this @allyoucanmap
