### ISSUE TITLE
[Resource Manager] Implement "copy" resource method

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/nexus-geonode#224]
As a user I need the `ResourceManager.copy` method being able to:

1. Create another resource with all the metadata values equals to the original one, except the `UUID`
2. The copied resource will have also the same permissions of the original one
3. In case it is a `Document`, the source files pointers will be the same of the original one
4. In case it is a `Layer`, a new layer should be created on GeoServer too and associated to the new resource

**Comment by giohappy** [comment]
Keep in mind the following for the implementation:

 - copying could potentially undergo a (pluggable) workflow as when a new resource is created. This is required to pave the road to created derived resources from processing routines (stupid examples: centroid point dataset from a polygon dataset, NDVI from multi-band raster, etc.). So the cloning must consider the option to configure, in the near future, creation workflows
 - I think document files should be copied. Although no document editing is planned in the short term, having a clone of the document gives the option to have sort of a versioning. The cloned document can be replaced with a new version of the file. If you reference the same file you would overwrite both the resources.

**Comment by afabiani** [comment]
@giohappy 

1. Ok, we will envisage also a first interface to include that.
2. Agreed to copy the doc files.
