### ISSUE TITLE
Frontend - Creating a new GeoStory from the old template redirects to an empty one

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/nexus-geonode#229]
* **Creating a new GeoStory by using the old interface**
    ![image](https://user-images.githubusercontent.com/1278021/123068096-e10a1900-d411-11eb-9bb3-0be352f0de8b.png)
    ![image](https://user-images.githubusercontent.com/1278021/123068143-e8c9bd80-d411-11eb-9e73-fc95ea05cf90.png)

* **redirects always to a new/empty one**
    ![image](https://user-images.githubusercontent.com/1278021/123068206-f8490680-d411-11eb-82f3-2b050a5cbeea.png)

* **even though the GeoStory has been successfully saved**
    ![image](https://user-images.githubusercontent.com/1278021/123068277-0860e600-d412-11eb-9c59-ce851abc621a.png)

* **Editing the newly created GeoStory, works as expected instead.**

**Comment by giohappy** [comment]
@afabiani the old pgaes won't be supported anymore. We're going to make a drastic move next days: remove old the legacy pages that will be replaced by the new forntend components. 
I'm going to close this.
