### ISSUE TITLE
WMS link for remote layers should store only the base path and custom params

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#248]
For remote layers we're saving the whole URL provided to configure the remote service as WMS link for the layer. Sometimes this include the GetCapabilities requests params.

For consisteny with the other WMS links for local layers only the base bath of the service whould be stored. By the way some services include additional custom parameters that must be retained inside WMS requests (e.g. http://www502.regione.toscana.it/wmsraster/com.rt.wms.RTmap/wms?map=wmsofc&map_resolution=91&language=ita&). 

We should use the URL provided inside the GetCapabilities for the GetMap operatation, e.g.

![image](https://user-images.githubusercontent.com/571129/123278687-6e7b6500-d507-11eb-91de-42aa5075309d.png)

I think we can retrieve the link from the owslib web service [operations](https://github.com/geopython/OWSLib/blob/master/owslib/map/wms111.py#L102).

NOTICE: This is a also prerequisite to populate the (currently missing) `links` property inside the api v2 response for layers,

**Comment by giohappy** [comment]
This issue is related to these:

- https://github.com/GeoNode/geonode/issues/6631
- https://github.com/GeoNode/geonode/issues/6755

**Comment by afabiani** [comment]
Upstream PR available [here](https://github.com/GeoNode/geonode/pull/8039)

**Comment by giohappy** [comment]
fixed through https://github.com/GeoNode/geonode/commit/70ccc8ef8b2e70602269f38eae438f4da66bcb00
