### ISSUE TITLE
Rename API v2 endpoint from layers/ to datasets/

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#249]
For consistency with the renaming of the frontend we should also rename the API v2 endpoint from layers/ to datasets/

- [ ] change the endpoints
- [ ] adapt the client to the new endpoints

**Comment by mattiagiupponi** [comment]
Geonode: https://github.com/geosolutions-it/geonode/pull/885
Mapstore: https://github.com/geosolutions-it/geonode-mapstore-client/pull/244
