### ISSUE TITLE
Change button links to reference the new editors

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#252]
The new client will still use some legacy pages for "atomic" operations. E.g. uploading a new dataset (aka layer) will open the legacy upload page. same for editing metadata, and so on.

These legacy pages have buttons bringing back to the resource. The new client has the new "editors", and the legacy detail pages for resources will be removed soon. We need to adapt the button to link to the new editors.

@marthamareal ask @allyoucanmap if you need a hand to configure the links to the new editors.

**Comment by marthamareal** [comment]
@giohappy I proceeded with the approach of using hooksets and client_lib_tags where the tags by default have the links set in geoNode templates currently and these can be overridden by the client.
