### ISSUE TITLE
List the "operations" pages

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#261]
Operations pages are all the pages where the user can execute a single action over a resource.
The ones that come to my mind are: 

 - advanced metadata
 - wizard metadata
 - upload (layer, map, doc, etc.)
 - replace layer
 - append data to layer
 - ...

These will be the only legacy pages related to resources that will be maintained for the time being alogn with the new client.

**Comment by marthamareal** [comment]
@giohappy  apart from the 
- `layer_style_manage` and 
- `permissions` 
pages, I don't see any other Operations pages we have left out.

**Comment by giohappy** [comment]
@marthamareal what is the `permissions` page?

**Comment by marthamareal** [comment]
> @marthamareal what is the `permissions` page?

https://github.com/geosolutions-it/geonode/blob/master/geonode/templates/_permissions.html#L108
