### ISSUE TITLE
Review GeoNode dependencies

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#27]
I've run [pipreqs](https://pypi.org/project/pipreqs/) to check the libraries actually used inside GeoNode code and the result is that many dependencies are probably unuseful.
[This is the output](https://github.com/geosolutions-it/nexus-geonode/files/6013703/geonode_pipreqs_requirements.txt) requirements file from pipreqs. I expect that moe module might be needed beyond what pipreqs could parse, but it is a good start to review and cut the dependencies .

**Comment by mattiagiupponi** [comment]
From an analysis if the dependencies declared for geonode, the only library that are not used ATM explicitly inside geonode are the following:
```
django-jsonfield-compat==0.4.4
pyrsistent==0.17.3
pyyaml>=4.2b1
parse-type==0.5.2
```
The other libraries are used at least 1 time or are depedencies from other libraries (ex `numpy`)

**Comment by giohappy** [comment]
ok @mattiagiupponi I thought we hade more stale deps.
@afabiani I would remove those four if we confirm they're not used.
