### ISSUE TITLE
Documentation for harvesters

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#272]
A new chapter dedicated to the Harvester will replace the [current one for Remote Services](https://docs.geonode.org/en/master/usage/managing_layers/using_remote_services.html).

The docs must explain:

 - general functionalities of the harvester
 - functionalities of the specific harvesters (GeoNode, WMS, ArcGIS)
 - configuration of the harvesters

**Comment by ricardogsilva** [comment]
Documentation has been submitted and merged and is live at:

https://docs.geonode.org/en/master/intermediate/harvesting/index.html

I think we can close this issue
