### ISSUE TITLE
Design client model, operations and configurable options

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#274]

**Comment by ricardogsilva** [comment]
@meomancer the goal here is to design and implement a harvester for ESRI services that matches whatever GeoNode was already supporting with the previous remote services approach (which the harvesters are now supposed to replace).

Looking at `geonode.services.serviceprocessors.arcgis` it seems there is actually support for two types of remote services in `ArcImageServiceHandler` and `ArcMapServiceHandler`. Please check with @giohappy what type of harvester(s) do we need to implement - not sure if we want to support both of these previous services. If we need to support both of them I will be in favor of having two different harvesters, one for each type of remote service.

Also, speak with @lkwalke4 (AKA Lindsay) as she has experience with ESRI products and will likely be able to provide insight on implementation strategies

**Comment by meomancer** [comment]
hi @ricardogsilva @lkwalke4
Should we keep similar implementation on the service to our harvester? Which is using gn-arcrest

**Comment by giohappy** [comment]
As yuo prefer @meomancer. If it helps and covers the what we need let's keep using it, but I'm open to alternative solutions (if they don't require more time to implement).

**Comment by ricardogsilva** [comment]
This has been implemented, so I think we can close the issue
