### ISSUE TITLE
Harvesting of ArcGIS resources metadata

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#275]

**Comment by ricardogsilva** [comment]
@meomancer please see my comment on #274 which is also related to ESRI harvesters

**Comment by giohappy** [comment]
please move this @ricardogsilva

**Comment by ricardogsilva** [comment]
The ArcGIS harvester has been implemented and merged upstream, as seen in

https://github.com/GeoNode/geonode/blob/master/geonode/harvesting/harvesters/arcgis.py

Therefore we can close this as DONE:tm:
