### ISSUE TITLE
Implement ResourceBase.subtype field

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#277]
A new `ResourceBase.storetype`  field will replace `Layer.storeType` and `Document.doc_type`. The new field will simplify filtering and parsing of API v2 resources/ endpoint. 

The implementation must include a fixture that will move the values from the preexisting fields to the new one.

**Comment by mattiagiupponi** [comment]
https://github.com/geosolutions-it/geonode/pull/882
