### ISSUE TITLE
Show document preview inside preview panel

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#281]
The preview panel for documents currently show the the thumbnail. It must show the preview of the document instead.

**Comment by luorlandini** [comment]
Sorry @giohappy do you mean, in the detail panel "home" (#/detail/document/15) 
or in the viewer one, "editor" (viewer/#/document/15)?
thanks

**Comment by giohappy** [comment]
@luorlandini  when I say "preview" I mean the home panel only.

**Comment by luorlandini** [comment]
@giohappy the API we are using to get document data, in the home panel, doesn't return the information to  show document preview, or I'm wrong

for example:
https://stable.demo.geonode.org/api/v2/resources/2281

**Comment by giohappy** [comment]
@luorlandini do you mean the direct link that is visible when you hover on a document inside the lgacy detail page?

![image](https://user-images.githubusercontent.com/571129/124298190-42419300-db5c-11eb-80db-be9ab79f67aa.png)

**Comment by luorlandini** [comment]
@giohappy yes, I mean, to embed a document I expect to have the field "embed_url" populated,  the document resources/2281 is pdf, in the api response, seems that the embed field or other field, is missing or other field 
https://stable.demo.geonode.org/api/v2/resources/2281

**Comment by giohappy** [comment]
@luorlandini issue opened for @marthamareal https://github.com/GeoNode/geonode/issues/7741

**Comment by giohappy** [comment]
@luorlandini the embed_url should be populated now. Please check

**Comment by luorlandini** [comment]
@giohappy resolved with api upgrade
