### ISSUE TITLE
Add keyword to harvested resources

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#285]
Every resource created from harvestable resources must have a keyword with the name of the harvester (PDN, PCRAFI, etc.).
The keyword shouldn't contain the "harvester" suffix. I think it could also me removed from harvester names.

**Keywords must be lowercase**.

**Comment by ricardogsilva** [comment]
We will also need to include a way to update the keyword whenever a harvester's name is changed by the admin.

**Comment by giohappy** [comment]
I wouldn't bother too much... Next time resources will be harvested keywords will be added accordingly. 
Keeping track of previous keywords and so on is too much. I would just do a "create if not exists" ad keeping the previous ones.

**Comment by ricardogsilva** [comment]
@meomancer this needs to be implemented as an additional keyword that is added to the resource regardless of what each specific harvester may already add - this means that implementation will probably need to be done in the `harvesting.tasks._harvest_resource()` function (we should change the name of this method, removing the leading underscore, to signal that it should be public, but lets leave that for a future PR). I think you can modify the response of the `worker.get_resource()` call and add an additional keyword to the resource descriptor.

**Comment by meomancer** [comment]
Could we close this @ricardogsilva ?

**Comment by ricardogsilva** [comment]
not yet, @meomancer, as it seems to be related to #391

**Comment by ricardogsilva** [comment]
Since #391 has now been closed, I think it is also safe to close this
