### ISSUE TITLE
Core cleanup analysis

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#3]
https://docs.google.com/document/d/14XcHJmMEc9H_u9DFFzeLuI2pm-87O191G5ssDjtAp8Y/edit#

**Comment by afabiani** [comment]
@giohappy about GeoNetwork

Currently the GeoNetwork support was supposed to be somehow pluggable into the catalogue.

The initial approach was good; nevertheless there are several “if-else” statements hardcoded into the “generic” class of the “geonode.catalogue” module explicitly checking for the “geonetwork” type.

What should we do here?
1. Transform generinc in a real pluggable class (Estimate: 1)
2. Get rid of GeoNetwork stuff (Estimate: 0.5)

**Comment by giohappy** [comment]
The latter @afabiani. We're note going to support alternative CSW services for the time being.
