### ISSUE TITLE
Add ratings API v2 endpoint

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#310]
Ratings are provided by the `pinax-ratings` module. 
We want to implemenet a CRUD API for ratings under the `resources/{pk}/ratings` endpoint.
It will provide:
- a GET endpoint to obatin the list of ratings, retrieved from the [OverallRating model](https://github.com/pinax/pinax-ratings/blob/v4.0.0/pinax/ratings/models.py#L14)
- a lightweight wrapper on top of the `pinax-ratings` post API, which will remove the need for the client to include the `content_type` code as [requested by `pinax-ratings` URLs](https://github.com/pinax/pinax-ratings/blob/v4.0.0/pinax/ratings/urls.py#L9).

The /comments endpoint wil work also for the specific resource endpoints (`datasets/`, `documents/` and `geoapps/`)

**Comment by marthamareal** [comment]
> The /comments endpoint wil work also for the specific resource endpoints (`datasets/`, `documents/` and `geoapps/`)

@giohappy do you mean that we should also have ratings in specific resources API eg `geoapp/{pk}/ratings`

**Comment by giohappy** [comment]
not strictly required. We can just implement `resources/{pk}/rating`
