### ISSUE TITLE
Wrong encoding of result from search autocomplete

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#326]
1. Search for "story"
2. Select "A story"
3. Search box is populated with "A%20story"

![image](https://user-images.githubusercontent.com/571129/125827265-7414f148-147e-4eca-b664-28d02b225838.png)

![image](https://user-images.githubusercontent.com/571129/125827277-0e3c485e-dd26-44d5-853b-791ed1074a8c.png)

**Comment by marthamareal** [comment]
@giohappy, Is the fix here making sure that the search box input gets a displayed value eg A story ?

**Comment by giohappy** [comment]
Yes. See the second image. In this moment the value retrieved from the autocomplete selection is visualized with encodings.
