### ISSUE TITLE
Add "full screen" button to editors

### ISSUE THREAD

**Issue by luorlandini** [geosolutions-it/nexus-geonode#336]
Add "full screen" button to editors to open open a full screen view of the contents. For the moment it could use the embedded view.

**Comment by allyoucanmap** [comment]
@luorlandini 
Proposal: allows the ActionNavbar to get tools on the right part after the title and use an icon with a tooltip

![image](https://user-images.githubusercontent.com/19175505/129915154-a98dc991-692f-4bf3-bd2c-0fc4337c8c2d.png)

**Comment by giohappy** [comment]
@allyoucanmap I see this is already implemented, right? Can we close this?

**Comment by giohappy** [comment]
BTW it's missing for Dashboards. Is it doable for dashboards too?

**Comment by allyoucanmap** [comment]
> @allyoucanmap I see this is already implemented, right? Can we close this?

I think we merged this on friday and should be completed

> BTW it's missing for Dashboards. Is it doable for dashboards too?

@giohappy I think it's doable for all viewer but probably it's missing in the configuration. We could keep this open and verify if it's working in all viewers
