### ISSUE TITLE
Drop legacy views and templates

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#345]
The following legacy views have been replaced in master by the new client SPA:

- `/search`
- `/datasets`
- `/documents`
- `/maps`
- `/apps`
-` /datasets/(id}`
-` /documents/(id}`
-` /maps/(id}`
- `/apps/preview/(id}`

We want to remove from master anything **specific** to the view above:

 - view methods
 - template
 - javascript assets
 - tests

urls must be managed with care, because some of them (only the detail urls?) drive the `hooksets` mechanism, which is still used by the new client app.

**Comment by giohappy** [comment]
As a quick recap @italogsfernandes.

Some context:

 - master uses a mix of legacy views and templates + the new client app
 - geonode connects the legacy part and the new client through hooks and custom tags
 - the [hookset](https://github.com/GeoNode/geonode/blob/master/geonode/client/hooksets.py#L25) is a set of unimplemented methods in GeoNode, that are proxied to the [hooksets](https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/hooksets.py) implemented by the [configured client app](https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1434)
 - **master assumes that the only client app is `geonode-mapstore-client` and that it is configured**, because the master UI depends on the index.html and base.html [templates](https://github.com/GeoNode/geonode-mapstore-client/tree/master/geonode_mapstore_client/templates) provided by the client

The review and cleanup of the communication between GeoNode, legacy views and templates and the new client app is the task of https://github.com/geosolutions-it/nexus-geonode/issues/346.
In this task we only need to go through the following specific [urls](https://github.com/GeoNode/geonode/blob/master/geonode/urls.py#L92:

- search/
   - TemplateView -> search.html template and related subtemplates and javascript assets (search scripts, angular)
- datasets/
   - dataset_browse
   - dataset_detail
   - dataset_remove
   - style_edit
   - autocomplete_dataset
 - documents/
   - document_browse
   - document_detail
   - autocomplete_document
 - maps/
   - map_browse
   - map_detail
   - new_map
   - add_dataset
   - new_map_json
   - map_view
   - map_edit
   - map_remove
   - autocomplete_map
 - geoapps/
   - apps_browse
   - apps_detail
   - new_geoapp
   - geoapp_view
   - geoapp_remove
   - geoapp_edit
   - geoapp_update
   - geoapp_download

For all the above urls the following should be removed (if not needed by other views):
 - views (and any code that would become orphan)
 - templates
 - javascript scripts and libraries

Two big changes that I also suggest are:
 - remove index.html and base.html (they're provided by the client)
 - remove angular.js and related libraries. I think it's only used inside search.html and (unused) index.html, but please check if you find any other reference.

@afabiani @allyoucanmap any comments?

**Comment by allyoucanmap** [comment]
> remove index.html and base.html (they're provided by the client)

@giohappy the client does not override base.html but extend it for some legacy page (eg: remote services, login, logout, ...) https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/templates/base.html#L1

**Comment by afabiani** [comment]
- part of this work would be also to adapt `geonode-project` accordingly
- not fully sure why we need to remove `index` and `base` too, hose maybe just updated to host the SPA stuff?

**Comment by giohappy** [comment]
>@giohappy the client does not override base.html but extend it for some legacy page (eg: remote services, login, logout, ...) https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/templates/base.html#L1

@allyoucanmap right, it extends it. I'm going to remove it from the list above.

@afabiani one option cuould be to replace its content with an almost empty body. I wouldn't move the clietn's own index.html inside the core now. This is something I would do the day we collapse all the client things inside a single place, but now it would only be a unnecessary coupling.

**Comment by italogsfernandes** [comment]
@giohappy I removed most of the views and templates listed on your [last comment](https://github.com/geosolutions-it/nexus-geonode/issues/345#issuecomment-923871402). And the changes are almost ready for review at: https://github.com/GeoNode/geonode/pull/8201.

However, inspecting the code, I found that the views listed here below may be removed and they seem to be no longer used in other parts of the code.

Should I also remove them or some of them in this task? If no, I'll remove the draft `[WIP]` flag of the PR and open ti to be reviewed, if yes then I'll drop these views' code first.

> we can remove angular.js and related libraries... ...check if you find any other reference.
It is used by the `groups` and `profiles` pages. So, at the moment, it was not possible to remove it without breaking these pages.

**Possible to be removed**:
* geoapps:
    * geoapp_metadata
    * geoapp_metadata_advanced
    * geoapp_metadata_detail
* datasets:
    * dataset_granule_remove
    * dataset_append
    * dataset_feature_catalogue
    * get_dataset
    * dataset_metadata
    * dataset_metadata_advanced
    * dataset_metadata_detail
    * dataset_metadata_upload
    * dataset_replace
    * dataset_sld_upload
    * dataset_batch_permissions
    * dataset_metadata_upload
* documents:
    * document_download
    * document_metadata
    * document_metadata_advanced
    * document_metadata_detail
    * document_remove
    * document_replace
    * document_search_page
    * document_upload
* maps:
    * mapdataset_attributes
    * map_metadata
    * map_metadata_advanced
    * map_metadata_detail
    * map_wmc
    * new_geoapp

**Unsure about this possibility and dependencies**:
* new_map_json
* dataset_acls_dep
* dataset_batch_metadata
* dataset_resolve_user_dep
* dataset_upload
* document_batch_metadata
* map_json
* `/maps/checkurl/`
* map_batch_metadata
