### ISSUE TITLE
Sometime map initialization is not completed correctly

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#355]
A visible effect is the wrong positioning of the map, which doesn't fit the resource bbox.

**Comment by allyoucanmap** [comment]
This has been partially solved with this PR https://github.com/GeoNode/geonode-mapstore-client/pull/357 but are still missing the data editor and style editor pages

**Comment by giohappy** [comment]
Can we close this or there's more work to do @allyoucanmap?
