### ISSUE TITLE
Networ error and multiple maps created when using Save As

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#358]
The video below shows a severe problem with maps duplication:

1. Open a map
2. Click "Save" -> "Save As"
3. Hit Save
4. Network error is returned
5. Multiple maps are created (and visible, after a while)

![save as map error.gif](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/ea83cdd3-cdb9-434d-84c8-8450ff9ec3b8)

**Comment by giohappy** [comment]
@mattiagiupponi this also happens on Save.

**Comment by mattiagiupponi** [comment]
@giohappy I talk with @allyoucanmap about this.
Looks like that is a bug related to the sessions on the client-side.
Talking with @allyoucanmap looks like that the sessions related to the Maps needs to be refactored and he will take care of it.
I'm going to assign the issue to @allyoucanmap
