### ISSUE TITLE
Make detail panel overlay instead of push

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#367]
The push effect of the detail panel breaks at least two things:

- MapStore client layouts
- Geostories and Dashboards get horribly squasehd

As agreed with @allyoucanmap we want to make the detail panel overlay. The problem with overlay is that is might be not clear to the user when navigating maps and datasets. Map tools, search and panels will be hidden when the detail panel is open. 
For this reason either we hide the panel by default or we adopt animations to give evidence of the overlay. 
I would start testing the first option @allyoucanmap, starting with the panel closed when the editor is opened. 

Any interaction with the map and the tools menu will make the detail panel close. For example clicking on the map, or clicing the Catalog menu will close the detail panel.

**Comment by allyoucanmap** [comment]
New behaviours:
- detail panel is closed by default
- title of the resource in the top navbar
![image](https://user-images.githubusercontent.com/19175505/127503703-ddec48ea-dfff-4414-9e21-86ef9db572d4.png)
- close overlay panel on clickout

**Comment by giohappy** [comment]
@allyoucanmap for the moment it's fine, then we eill sww how to give more relevance to thte title.
