### ISSUE TITLE
Fix geostory upgrade

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#369]
Changes introduced with the implementation of dashboards break pre-existing geostories.

- polymorphic_ctype must be updated from `Geostory` to `GeoApp`
- geostories blob field must be stored as JSON

**Comment by mattiagiupponi** [comment]
Issue: https://github.com/GeoNode/geonode/issues/7873
PR: https://github.com/GeoNode/geonode/pull/7874
