### ISSUE TITLE
Allow extensibility of localConfig.json via patch for geonode project

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#38]
The configuration of new apps is stored in a static JSON file called localConfig.json file. Currently we need to override the whole file in a project to change some part of this configuration. It would be nice to introduce a new file called ~localConfig.patch.json~ `localConfig.override.json` that allow to use json path rules.

We could start from the work made for MapStore https://github.com/geosolutions-it/Patcher.

Example of ~localConfig.patch.json~ `localConfig.override.json` in a geonode-mapstore-client project to change homepage color

```js
[
    {
        "op": "add",
        "jsonpath": "/geoNodeConfiguration/theme/color",
        "value": "#605eda"
    }
]
```

**Comment by giohappy** [comment]
@allyoucanmap let's proceed. I would call the "patched" config file  `localConfig.override.json` to make it consistent with other overrides (e.g. Docker).

**Comment by allyoucanmap** [comment]
> I would call the "patched" config file `localConfig.override.json`

ok
