### ISSUE TITLE
Implement API for compact permissions

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#383]
As agreed permissions will be managed according to a "compact" set: 

- `view`: view resource
- `download`: view and download
- `edit`: view download and edit (metadata, style, data)
- `manage`: change permissions, delete resource, etc.

A user can have only one compact permission assigned.

The client will receive and set compact permissions through the [Permissions (Share) plugin](https://github.com/geosolutions-it/nexus-geonode/issues/93) .

The API will let the client retrieve, filter and sort compact permissions for users, organizations (group profiles) and the DJango groups used as roles (`Anonymous`, `Contributors`). `Moderators` are left outside since they have special roles over all the resources The GET method will return:

- users):
  - username
  - first name
  - last name
  - permissions (`view` | `download` | `edit` | `manage`)
- organizations:
  - title
  - name
  - permissions (`view` | `download` | `edit` | `manage`)
- groups:
  - title
  - name
  - permissions (`view` | `download` | `edit` | `manage`)

GET will allow filtering and sorting on any of the returned fields.

The API will allow the client to update the permissions or set new permissions on one or multiple users, organizations and groups.

**Comment by giohappy** [comment]
please @allyoucanmap and @afabiani report here your coclusions and the implementation plan.

**Comment by afabiani** [comment]
I've been working on a PermSpec object able to convert a standard and verbose 'perm_spec' into 'compact mode'.

   - The method also recognizes special/internal security groups, like 'anonymous' and 'registered-members' and places
     their permissions on a specific node called 'groups'.
   - Every security group, different from the former ones, associated to a GeoNode 'GroupProfile', will be placed on a
     node called 'organizations' instead.

 e.g.:

```json
{
    "users": [
        {
            "id": 1001,
            "username": "afabiani",
            "first_name": "",
            "last_name": "",
            "permissions": "manage"
        }
    ],
    "organizations": [],
    "groups": [
        {
            "id": 3,
            "title": "Registered Members",
            "name": "registered-members",
            "permissions": "edit"
        },
        {
            "id": 2,
            "title": "anonymous",
            "name": "anonymous",
            "permissions": "download"
        }
    ]
}
```

**Comment by giohappy** [comment]
can we close this @afabiani?
