### ISSUE TITLE
Emebed page for documents

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#388]
We need to introduce a django template for embedded document resources to center various media type in the page.
Currently is not possible to style element inside the iframe so the preview that use direct media source show the content in the original size.

now:

![image](https://user-images.githubusercontent.com/19175505/127532889-ca44c0d7-9f47-49d5-bd7e-ee752f98745a.png)

expected:

![image](https://user-images.githubusercontent.com/19175505/127532851-365f0fc9-5467-4e26-81ac-b91836a5a000.png)

All the type of documents should be centered in page

**Comment by luorlandini** [comment]
can be closed, for this issue:
https://github.com/GeoNode/geonode/issues/8053


![Schermata 2021-09-17 alle 10 54 29](https://user-images.githubusercontent.com/4085786/133755671-7b0ff23f-cdef-4baa-b82a-7f99c5ac365c.png)
