### ISSUE TITLE
Map editor not showing this map

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#390]
@allyoucanmap can you please take a look at [this specific map](https://dev.nexus.geosolutionsgroup.com/catalogue/#/map/61) on Nexus server? It appear inside the embed map of the preview panel but not inside the editor. 
Please investigate if it's something with the editor or with the data received from the API. In the latter case ask @mattiagiupponi to investigate. I remind you that this data were upgraded from a preivous master version, but I don't think this is an issue caused by migrations.

@allyoucanmap you can get the credentials [here](https://docs.google.com/document/d/1P0M94t6QWqvngp0KqTY44KshQbRIUwMjbqb5OwTtiS4)

![map_not_showibng_up](https://user-images.githubusercontent.com/571129/127572073-1bc29b20-4dfd-4c3d-a001-cdb765e9836e.gif)

**Comment by allyoucanmap** [comment]
It seems something related to migration, now data is returned as string instead of object cc: @mattiagiupponi 
![image](https://user-images.githubusercontent.com/19175505/127668616-f2cf94d2-25ac-4b7d-8f35-bee3f4913b85.png)

**Comment by mattiagiupponi** [comment]
Technically this migration was made in order to fix this issue:
https://github.com/GeoNode/geonode/blob/master/geonode/geoapps/migrations/0006_geoapp_blob_migration.py

@allyoucanmap did you notice that is happening only for this map?

**Comment by allyoucanmap** [comment]
@mattiagiupponi I think that map is not a geoapp but I'm not sure.

>  did you notice that is happening only for this map?
I only verified this one

**Comment by mattiagiupponi** [comment]
@giohappy @allyoucanmap Looks like the maps are already in place in the `Nexus DB`, the payload was saved/read as `str`, while now with the new version of the client is saved/read as `JSON`.
I'm going to open a PR in geonode with a migration (like what we did for the geostories) in order to fix this.
NOTE: the new maps are correctly saved/read

**Comment by mattiagiupponi** [comment]
ISSUE: https://github.com/GeoNode/geonode/issues/7911

**Comment by mattiagiupponi** [comment]
PR opened here: https://github.com/GeoNode/geonode/pull/7912
