### ISSUE TITLE
Keywords not set for harvested resources

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#391]
@ricardogsilva I thought it was already implemented by a recent PR, but I noticed that, for example, documents harvested from PDN don't have the expected `pdn` keyword assigned.

**Comment by meomancer** [comment]
hi @giohappy 
it is working fine on my side
did you use the latest geonode?

and also the keyword is the name of the harvester
So for example:
My harvester name is "test"
![Selection_019](https://user-images.githubusercontent.com/4530905/129152428-1b9adcd5-4496-4ca9-8fd9-4b4373ebc462.png)

The keyword is "test"
![Selection_020](https://user-images.githubusercontent.com/4530905/129152459-29b9daa8-f4e4-4f84-b669-716a9fa72386.png)

Is it working on your side?

**Comment by giohappy** [comment]
ok it looks fine now
