### ISSUE TITLE
Issue editing metadata on Dashbord 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/nexus-geonode#392]
If the metadata of a dashboard are edited, it is no longer visible in the dashboard list and it is no longer possible to open it

**How to Reproduce**
Follow the steps below:
![vanuatu_dash22.gif](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/07c199c9-8ac8-4816-910a-627682dd7c1b)

This is the error on console:
> GET https://risk.spc.int//uploaded/CACHE/images/curated_thumbs/WS_Country_Profile/ae99d4fd0a27cbc36ae5481d80ad0a30.png net::ERR_CONNECTION_REFUSED

**Comment by mattiagiupponi** [comment]
@ElenaGallo the issue should be fixed, can you take a look at it?

**Comment by ElenaGallo** [comment]
Thanks @mattiagiupponi  now the dashboards are visible in the list. however, sometimes clicking on the dashboard card does not open it.

This is the error on console:

> GET https://dev.nexus.geosolutionsgroup.com/api/v2/resources/118 404 (Not Found)

![dash](https://user-images.githubusercontent.com/56537133/128216433-ebd0e7fa-8f88-4677-b66f-f06e7000830b.gif)

**Comment by mattiagiupponi** [comment]
@ElenaGallo, that's quite strange behavior, it's happening only with the dashboards or also with the other resources?. 
The client raises a `404`, but by clicking on the URL provided the `API` and the `embed` return correctly the payload.
@allyoucanmap do you think that could be an issue with the client? Meanwhile I'm testing it on my local instance

**Comment by ElenaGallo** [comment]
@mattiagiupponi only with dashboards

**Comment by allyoucanmap** [comment]
> @allyoucanmap do you think that could be an issue with the client? Meanwhile I'm testing it on my local instance

I'm trying on their dev instance and it does not seem consistent because after clicking multiple time at the end it works:

https://user-images.githubusercontent.com/19175505/128312047-4a5312c1-a8e3-44af-8332-6b686e0017ef.mp4

The error payload is `{ detail: "Not found." }` so it seems it reach the backend and it's not something interrupted by the client. I think an improvement client side should be to make the error more clear but this does not solve the issue. I just tested locally and it's working fine but I have not the ASYNC option enabled, could be due to a some asynchronous task?

**Comment by allyoucanmap** [comment]
> @mattiagiupponi only with dashboards

@mattiagiupponi @ElenaGallo 
Sometimes it happens also with geostory:

![image](https://user-images.githubusercontent.com/19175505/128313464-08d09893-f797-4e3a-a6ac-ecdb4c5b87e8.png)

**Comment by mattiagiupponi** [comment]
Update:
Me and @afabiani found the issue regarding the 404. In a nutshell, everytime you tried to call in GET the resource, the system tried to create the thumbnail and set the resource in dirty_state. Now we are deploing the fix to the dev-server. Once is done, @ElenaGallo you can continue with your tests

**Comment by ElenaGallo** [comment]
@mattiagiupponi  now opening a new dashboard displays the previously opened dashboard.

On console:
>  WARN: Too many auto-margin redraws.

![newdash](https://user-images.githubusercontent.com/56537133/128347767-c3fcb7ec-747f-4454-b991-eb9d9fd76746.gif)

**Comment by ElenaGallo** [comment]
Closed in favor of #393
