### ISSUE TITLE
GeoStory toolbar problem adding sections

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/nexus-geonode#394]
After adding different sections in the geostory, the geostory toolbar (save, edit, share buttons), at the top left, is no longer available.

![story_toolbar](https://user-images.githubusercontent.com/56537133/128491737-363c7097-565c-4107-a674-7b5b8e8bcafd.gif)

**Comment by giohappy** [comment]
@allyoucanmap what is the feedback on this issue?
