### ISSUE TITLE
Create branches for GeoNode, mapstore adapter and mapstore client

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#4]
As agree with @afabiani the development work for Nexus will be done inside GeoSolutions' repositories. For the bootstrp of Nexus GN project we will need dedicated branches for [GeoNode](https://github.com/geosolutions-it/geonode), [django-mapstore-adapter](https://github.com/geosolutions-it/django-mapstore-adapter) and [geonode-mapstore-client](https://github.com/geosolutions-it/geonode-mapstore-client). 
The following steps are a prerequisite for the creation of the GeoNode project for Nexus:

- [x] check the alignment of (and in case align) our three repo to the upstream ones
- [x] create a branch named "nexus" from the master of each of them

**Comment by afabiani** [comment]
@giohappy done

geosolutions-it/{geonode; mapstore-adapter; mapstore-client} have been:

1. Aligned master branches to upstream
2. Created nexus branches
