### ISSUE TITLE
The detail_url property is missing from api/v2/resources response

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#400]
The resources object returned by the api/v2/resources endpoint have detail_url set as empty string

- http://localhost:8000/api/v2/resources

![image](https://user-images.githubusercontent.com/19175505/129381995-a35df18f-2892-4b8f-af6f-93cd6e36c53f.png)

**Comment by afabiani** [comment]
Please check the commit https://github.com/GeoNode/geonode/commit/5c94a164e2e3c71224bddefad8bf2a1dead7abe4

**Comment by giohappy** [comment]
@allyoucanmap please confirm the commit solves the issue.

**Comment by allyoucanmap** [comment]
@giohappy @afabiani I'm testing right now and it's solved GeoNode side but I need to push a commit to make the client use it. Working on it right now

**Comment by allyoucanmap** [comment]
@giohappy @afabiani client updated so we can close this
