### ISSUE TITLE
Create dataset template does not exist

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#401]
The http://localhost:8000/createlayer/ link returns this error:

![image](https://user-images.githubusercontent.com/19175505/129382221-710f048f-4ac5-4c23-9d37-6aab73612758.png)

**Comment by afabiani** [comment]
Please check the commit https://github.com/GeoNode/geonode/commit/5c94a164e2e3c71224bddefad8bf2a1dead7abe4
