### ISSUE TITLE
Permissions assigned to datasets should take into account the resource type

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#412]
Permissions on a dataset are returned independently from the type dataset, but some permissions are meaningless for some types and, moreover, make the client show tools that shouldn't be available for those types.

- local datasets:
  - vector: all permissions
  - raster: should't have `change_dataset_data` permissions
- remote datasets:
  - any type:  should't have `change_dataset_data` and `change_dataset_style` permissions

@afabiani is the full set of permission types assigned without taking into account the resource type when a new dataset is created? Apparently yes, because I see that all the type of permissions can be set even for remote datasets from the Edit permissions window.

IMHO this issues should be addressed at creation time, and permissions should be hidden from the permissions panels. I guess this also inpacts the translation between compact permissions and perm specs @afabiani.

**Comment by afabiani** [comment]
@giohappy currently the PermSpec converter is aware of the `resource_type` and it also applies some changes accordingly
(e.g.: https://github.com/GeoNode/geonode/blob/master/geonode/security/permissions.py#L116)

If some permissions are not correct we might need to improve those classes in order to take into account more special cases.

Can you elaborate more on how to reproduce some use cases and different conditions?

**Comment by giohappy** [comment]
@afabiani the issue has been raised by @allyoucanmap in https://github.com/geosolutions-it/nexus-geonode/issues/407#issuecomment-907187439

In any case I see that the permissions panel is the same whatever the resource type. I don't expect to see the "edit style" and "edit data" for a remote dataset, for example.

**Comment by afabiani** [comment]
@giohappy taking a look given the comments from @allyoucanmap

**Comment by afabiani** [comment]
@giohappy I found the issue, going to open a PR upstream.

**Comment by afabiani** [comment]
@giohappy PR available [here](https://github.com/GeoNode/geonode/pull/8027)
