### ISSUE TITLE
Assorted issues for the share plugin

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#418]
- not options available inside the select box for "Registered memebers"
- options clipped by the pinned box
- Anyone not available for documents

Clipping:
![image](https://user-images.githubusercontent.com/571129/132360143-333e684c-c1a1-4027-a49c-eaf74893e6a3.png)

Missing "Anyone" for documents:
![image](https://user-images.githubusercontent.com/571129/132360229-c1b4f1fc-8607-422b-9b10-4fb9fc359adb.png)

**Comment by luorlandini** [comment]
@giohappy about point 3 "Anyone not available for documents" 
I cannot replicate, in my case, I show it.
that component depends from "/permissions" api, maybe in your case, the api didn't return anonymous group

![Schermata 2021-09-10 alle 11 24 59](https://user-images.githubusercontent.com/4085786/132834189-826871e8-c2b4-4904-a744-7e0e8d172a08.png)
