### ISSUE TITLE
Implement a GeoNode harvester for api v2

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#433]
A nre harvester is required to adopt API v2 instead of the legacy one + CSW (as we have int the currrent and only GeoNodeLegacyHarvester implementation).

This harvester must adopt API v2 from 3.2.x on, and incrementally adopt new endpoints and responses from the API v2 in master branch.

**Comment by ricardogsilva** [comment]
@giohappy is this in scope for the NEXUS too?

**Comment by ricardogsilva** [comment]
The GeoNode harvester that was implemented and merged upstream presents a unified interface that is able to harvest from both legacy to 3.2 to 3.2+ versions of remote GeoNode servers - therefore this issue can be closed
