### ISSUE TITLE
Extra slash inside GeonHarvester API base urls

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#434]
The [composition of the API](https://github.com/GeoNode/geonode/blob/c7e47bec7fd587fc31d1e034e53ed89954575f4b/geonode/harvesting/harvesters/geonode.py?plain=1#L280) urls contain an extra slash which makes requests fail.

`self.http_session.get(f"{self.base_api_url}/{endpoint_suffix}")` -> `self.http_session.get(f"{self.base_api_url}{endpoint_suffix}")`

**Comment by ricardogsilva** [comment]
This is fixed in geonode/geonode#7947 (currently in the GeoNode PR queue)
