### ISSUE TITLE
Remote documents are not available to geostories

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#435]
Remote documents, i.e. those retrieved from remote services and having the remote url set (`document.doc_url`) are not listed inside images and video resources for geostories.

These `embed_url` API v2 for these documents contain the redirected resource, so from the point of view of the MapStore client they should be treated and behave, trnapsarently, as local documents.

**Comment by marthamareal** [comment]
> Remote documents, i.e. those retrieved from remote services and having the remote url set (`document.doc_url`) are not listed inside images and video resources for geostories.

@giohappy, am failing to understand this sentence especially `not listed inside images and video resources for geostories.`

**Comment by giohappy** [comment]
@marthamareal when you edit a geostory you can add documens. You select GeoNode as the source for the images, videos or audios to use and the editor panel shows the list of available documents. You will see that remote documents are not listed.

**Comment by giohappy** [comment]
@marthamareal to clearify, I'm referring to this window

![image](https://user-images.githubusercontent.com/571129/133433014-5b7b6a91-ef60-4ee7-b487-5dd86dd14ae8.png)

**Comment by marthamareal** [comment]
@giohappy THey are not listed because the api for listing them filters by subtype and for remote docs, the subtype is null. 
![docs](https://user-images.githubusercontent.com/20810749/133436615-05c3907e-ed80-4db2-9768-7c928b00bc93.png)

**Comment by giohappy** [comment]
Interesting @marthamareal. 
@afabiani I guess the RM is not filling the `subtype` for harvested resources.

**Comment by afabiani** [comment]
@giohappy taking a look

**Comment by afabiani** [comment]
@giohappy @marthamareal I guess the issue is in the `_create_layer` methods of the `geonode.servcies.serviceprocessors`, as an instance for the `WMS` here

https://github.com/GeoNode/geonode/blob/master/geonode/services/serviceprocessors/wms.py#L297

**Comment by giohappy** [comment]
@marthamareal as agreed I ask you to investigate this, this is an opportunity to understand the Resource Manager and Harvesters concepts for you.

 - resource manager is the new component in charge of managing all the operations on resources
 - harvesters are the components developed by Ricardo (Kartoza) for the ingestion of remote resources. They interact with the resource manager to complete the creation of geonode resources for the ingested data

When the resource manager create and update methods are called, they trigger downstream methods (like resource_post_save) that do some post processing on the resource instance. For example it extracts file extensions, etc.
I suppose subtype should be filled there, but I'm not sure where exactly

You should check how it works for local resources (if it's up to the resource manager to calculate and set it or if it's the resource manager callee)

**Comment by giohappy** [comment]
>@giohappy @marthamareal I guess the issue is in the _create_layer methods of the geonode.servcies.serviceprocessors, as an >instance for the WMS here
>
>https://github.com/GeoNode/geonode/blob/master/geonode/services/serviceprocessors/wms.py#L297

I don't think services are involved in my tests. I was using the harvesters which, as far as I know, do not interact with services (for the moment).

**Comment by afabiani** [comment]
@giohappy @marthamareal sure, sorry for the mistake... I read remote services instead of remote documents

**Comment by marthamareal** [comment]
@afabiani @giohappy I did a test and on harvesting dataset, the subtype is set eg 
![remote](https://user-images.githubusercontent.com/20810749/133613465-02a85206-515a-4e2e-84b3-c3aa7cf03e2e.png)

For documents, on uploading a remote doc(url), we could assign the subtype [here](https://github.com/GeoNode/geonode/blob/master/geonode/resource/utils.py#L318) if the extension is not null, Or make a request to the URL and get the content-type which we can save as a subtype.

**Comment by giohappy** [comment]
@marthamareal how did you harvest the dataset?

**Comment by marthamareal** [comment]
> @marthamareal how did you harvest the dataset?

Through remote services. 
![resou](https://user-images.githubusercontent.com/20810749/133635952-35276a7f-6a89-43b6-a95f-8e86068c0c59.png)

**Comment by giohappy** [comment]
After further investigation, support to use remote resources inside geostories require some additional work.

[document_post_save](https://github.com/GeoNode/geonode/blob/95f8924e9cd38b3b573ecb9c25d83d3e0242f736/geonode/resource/utils.py?plain=1#L303) is in charge of extracting the extension, **but it does it only for documents with local files**. Consequently, the API will not return documents that reference a remote file.

If we want to keep using the file extension to drive functionalities, we should extract it from the remote file, which is not straightforward. A method (that I tested) is to submit a request to the remote file and 
   - in case of a binary response try to parse it with [python-magic](https://github.com/ahupp/python-magic), or similar tools, and obtain the file type from magic bytes (if available)
   - in case of textual files... the only option is to parse the response headers and hope they provide the mimetype for the file

I think this appraoch is error-prone and requires additional requests just for probing files. 
On the other side I think we shouldn't expose external URLs directly to geostories for security reasons. We might end up introducing bad things inside them.

So, I'm going to close this issue for the moment and keep supporting only local files (maybe copied from remote sources) for the time being.
