### ISSUE TITLE
Datasets bbox is not reflected in previews and views

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#436]
I thought it was some problem with the autopisitioning widget in MapStore, but I turned the Location off in my browser. Yet all the previews and viewers get positioned on Italy despite the bbox is clearly not in Italy!

![image.png](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/8ec2ae4e-afb8-4e80-b5da-4fc8829aaad3)

**Comment by allyoucanmap** [comment]
@giohappy The client uses the `ll_bbox_polygon` that should be always populated and always in CRS84 but it is `null` for the dataset you showed in the screenshot

![image](https://user-images.githubusercontent.com/19175505/133215777-97fa4ed5-cb14-4511-8b74-e707c69f853e.png)

**Comment by giohappy** [comment]
thx @allyoucanmap. Fixed on the backend
