### ISSUE TITLE
Give more relevance to ationbar buttons

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#439]
The current graphics are a bit "pale". We agree on having a clean and light approach but I think the current list of labels are a bit too week and action buttons don't have the right relevance. We're in the editor, so they should be the most prominent actions for the user, but in this moment the menu button have higher relevance.

We should make some tests, maybe restore the border for the buttons, use more contrast for the font color...

![image](https://user-images.githubusercontent.com/571129/133633448-8603eb3f-f795-4b65-a6ab-a9a379124086.png)

**Comment by luorlandini** [comment]
@giohappy as you suggested 
![Schermata 2021-11-02 alle 10 21 53](https://user-images.githubusercontent.com/4085786/139820689-e3499397-d315-41e1-b757-b10103f2b3b3.png)

**Comment by giohappy** [comment]
much better IMHO, what do you think @allyoucanmap ?
