### ISSUE TITLE
Document's URLs from GeoNode 3.2.x legacy API are broken (cannot parse from PCRAFI)

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#446]
GeoNode 3.2.x legacy API return a wrong static file URL inside documents response.

As an example, https://stable.demo.geonode.org/api/documents/3421/ returns:

`"doc_file": "/static/documents/document/_TJRzaX8QWi5vgei5Ff_1g.7cee823b1e93.png"`

This relative URL returns 404.

The same request on GeoNode 3.3.x returns the correct URL. For example https://development.demo.geonode.org/api/documents/12/

`"doc_file": "/uploaded/documents/document/vfRWZF6mR76R6-zedgIqew.jpg"`

Unfortunately this is **a severe issue with any legacy GeoNode instance, including SPC's own PCRAGI (http://risk.spc.int/), which prevents the correct harvesting of remote documents**.

Please @marthamareal check what's wrong inside the 3.2.x legacy API and open an issue inside the geonode repo. 
We will suggest SPC either to upgrade their instance or apply the required patches.

**Comment by ricardogsilva** [comment]
@giohappy in the current `GeonodeLegacyHarvester` code I am able to get the download URL for a document resource by looking at the CSW `GetRecordById` response. For example, with a request like this:

http://risk.spc.int/catalogue/csw?service=CSW&version=2.0.2&request=GetRecordById&id=50877ed3-806e-11eb-ba73-f5f10530c199&elementsetname=full&outputschema=http://www.isotc211.org/2005/gmd

I can inspect the `gmd:distributionInfo` element in order to retrieve the download link - this legacy harvester uses a mix of CSW and GeoNode API calls to piece together all of the information (it is not very pretty, but seems to work).

The most recent version is currently on PR geonode/geonode#7947

**Comment by ricardogsilva** [comment]
yes, the CSW link I include in my previous comment is for a document. This is the relevant portion of the XML response. As you can see, there is a download link included, which is what we are currently using for the harvesting.

```xml
   <gmd:distributionInfo>
     <gmd:MD_Distribution>
       <gmd:transferOptions>
         <gmd:MD_DigitalTransferOptions>
           <!-- rest of the document ommitted for brevity -->
           <gmd:onLine>
             <gmd:CI_OnlineResource>
               <gmd:linkage>
                 <gmd:URL>http://risk.spc.int/documents/238/download</gmd:URL>
               </gmd:linkage>
               <gmd:protocol>
                 <gco:CharacterString>WWW:DOWNLOAD-1.0-http--download</gco:CharacterString>
               </gmd:protocol>
               <gmd:name>
                 <gco:CharacterString>Country Note Tonga.pdf</gco:CharacterString>
               </gmd:name>
               <gmd:description>
                 <gco:CharacterString>Country Note Tonga (Hosted Document Format)</gco:CharacterString>
               </gmd:description>
             </gmd:CI_OnlineResource>
           </gmd:onLine>      
         </gmd:MD_DigitalTransferOptions>
       </gmd:transferOptions>
     </gmd:MD_Distribution>
   </gmd:distributionInfo>
```

**Comment by marthamareal** [comment]
@giohappy  I am unable to reproduce this locally on both virtual environment and docker, 

I noticed that the url saved has a uuid between the name and extesion .
However, accessing the file via https://stable.demo.geonode.org/static/documents/document/_TJRzaX8QWi5vgei5Ff_1g.png, returns the image

The process of generating that path is done by [django-uuid-upload-path](https://github.com/etianen/django-uuid-upload-path/blob/master/uuid_upload_path/storage.py#L18)  Used in GeoNode [here](https://github.com/GeoNode/geonode/blob/3.2.x/geonode/documents/models.py#L55)

**Comment by giohappy** [comment]
@marthamareal I invite you to test an upload on stable demo and see if it can be reproduced there. If it happens I will send you the env file that we're using for the stable demo instance.

**Comment by marthamareal** [comment]
@giohappy on stable demo, it is reproduced https://stable.demo.geonode.org/api/documents/3652/

**Comment by marthamareal** [comment]
@giohappy  I was able to reproduce this by setting the env varaible `CACHE_BUSTING_MEDIA_ENABLED` to True, With this setting, the DEFAULT_FILE_STORAGE is directed to staticfiles location [here](https://github.com/GeoNode/geonode/blob/8d90b312af17184211d089e83a4c026b92af0ad0/geonode/settings.py#L355)
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

**Comment by giohappy** [comment]
@marthamareal so please just remove that settings from everywhere and update the docs if needed.
