### ISSUE TITLE
The owners API returns different results bewteen first response and subsequent responses

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#456]
How to reproduce:

1. Go to https://master.demo.geonode.org/
2. Open the browser's dev tools
3. Open the filters and expand the "Owners" select box
4. A request to https://master.demo.geonode.org/api/v2/owners?page_size=20&page=1 is executed
5. Response contains the `owners` key 
6. Open the same request on a new browser tab -> response contains `owners`
7. Refresh the page -> response contains `users` (and this will be returned for any susequent request)

I suspect something wrong happens between the OwnerSerializer and UserSerializer. 

Moreover OwnerSerializer should only return owners. The way it is now it returns all users (doing the same as UserSerializer). Any comment @marthamareal?

**Comment by marthamareal** [comment]
The owners API returns only users with at least one resource, as it filters users using this function [here](https://github.com/GeoNode/geonode/blob/master/geonode/base/api/views.py#L260)

The issue i see is the key name in response changing from `owners` to `users` on different calls. but data remains correct
