### ISSUE TITLE
Assessment of Map model and API simplification

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#462]
The current model for `Map` and `MapLayer` is intricate, confoluted and unnecesseraly complex. It builds on previous models (GPX*) and now we are managing an overly complex bridge between the MapStore config model, the Map and MapLayer models, and the GPX classes.

At the opposite we have the GeoApp model which is an abstract model which jsut provides a "type" information and access to the `BaseResource.blob` field which is used by MapStore to do itw own things. The `blob` field (`data` as called by the API) is completely opaque to GeoNode, and this is how things should be,

On the other side the MapStore config held inside the blob field must be inspected and recreated by GeoNode and the MapStore adapter to extract / provide the additional informations needed by the current Map model, and here we enter the grey area of parsing, and building the `blob` content. 

However, the MapStore client in master doesn't need this, and we don't have legacy views / templates that need the information the we're currently storing inside the `Map` and `MapLayer` (and GXP*) models, so most of the bridging performed by the MapStore adapter and the underlying GeoNode methods is probably useless.
Moreover, previous GeoNode functionalities that used these information are not exposed anymore (download of a map, exposing WMS services for a map, etc.).

In the most basic form the only information that we need could be stored in the following models:

- `Map` (an empty model, with just the automatic id field)
- `MapLaye`r
   - `map` -> FK `Map`
   - `dataset` -> FK `Dataset`
   - `style` -> string (or id of Link entry)

Actually the `MapLayer` and its fields are not needed in this moment, but we want them to be able to restore (inside the client) the representation of the relationships between maps, layers and their legends, as we have in GN 3.2.x and 3.3.x

My proposal is to make the following experiment on the master branch:

 - replace the current `Map` and `MapLayer` models with the (extremely) simplified models as above
 - exttend the map API to request and return the `MapLayer` objects when creating and updating a map
 - remove the `hooks` from the map API (which [references](https://github.com/GeoNode/geonode/blob/e21448c70004db5c6581b085a18d15504dd93d9e/geonode/maps/api/hook.py#L108) `MapstoreAdapterHook` by default, which [in tun uses](https://github.com/GeoNode/geonode/blob/e21448c70004db5c6581b085a18d15504dd93d9e/geonode/maps/api/hook.py#L54) the `GeoNodeSerializer`)

In the end the MapStore map config should be opaque to GeoNode, as it is for GeoApps. GeoNode will manage its own models, that are required to drive the core functionalities, and will request any third party client to populate those models.

This experiment should be performed in max 2 days. A report is expected with an anlysis to assess the effort for such a refactoring and its effects and side effects.

@etj @afabiani @allyoucanmap I invite you to put your comments here. I might have missed something important here that might block such an extreme refactroing!

**Comment by giohappy** [comment]
After a deeper analysis performed with @italogsfernandes we arrived to the following:

 - several views and templates inside GeoNode core cannot be removed right now since they're used to "proxy" the client requests and templates. The chain of views, templates and contexts build up on a sequence of transformations from / to GXP* classes, Map / MapLayer models and MapStore map config model. 
 - refactoring the above chain of methods, views and templates is hard. It must be removed as a block, including the MapStore adapter / converter
 - the solution is to create first a new Map / MapLayer model and expose them through the maps API, make the client use the new APIs and, finally, remove the legacy code

For the last point there are some points to be discussed with @allyoucanmap.

### Minimal set of information to drive the client
GeoNode currently adds specific pieces of information to the map config:

 - **info**: it returns permissions for the resource. IIRC this are not used anymore in master, right @allyoucanmap?
 - **backgrounds**: the backgrounds are a merge between the selected background when the map was created and the default background configured in GeoNode
 - **catalogServices**: the list of preconfigured catalog services, and the selected catalogue service
 - **center, zoom, projection:** I suppose these are generated from some defaults when a map config is not stored inside the blob. This is the case of new maps, new maps from layers and layer views
 - **layers' ftInfoTemplate**: this is inflated by GeoNode according to the configurations performed with the resource metadata utilities

@allyoucanmap please list the infromation that are expected to be provided by GeoNode, in particular when a map config is not saved in GeoNode (new maps, new maps from layers and layer views). 
**These information will be returned by the map API instead of being inflated into the map config**.

### Extend the Map API to support maps with or w/out a map config
From the point above, for all the case where a map config is not stored in the blob, the client should be able to set all its things up using the information obtained from the map API.

The API will return a structure, partially built from the Map and the MapLayer models data, and partially from external properties (e.g. list of backgrounds).
The returned object will be something like this:

```
{
 "map": {
    "id": map.id || null,
    "maplayers": [
        {
            id: maplayer.id 
            dataset: {
                <dataset model data>,
                featuretmpl: <obtained from dataset.attribute_config method>
            }
            style: (the style selected for this dataset in this maplayer)
        }
    ],
    backgrounds: settings.MAPSTORE_BASELAYERS,
    permissions: ???,
    
    defaults: {
        backgrounds: settings.MAPSTORE_BASELAYERS,
        catalogue: {
            "services": settings.CATALOGUE_SERVICES,
            "selected": settings.CATALOGUE_SELECTED_SERVICE
        },
        projection: settings.DEFAULT_MAP_CRS || '3857',
        center: _DEFAULT_MAP_CENTER (as calculated for the default map config in https://github.com/GeoNode/geonode/blob/7a8f750030a20bc9b8a62cd13c63303163ae6339/geonode/utils.py#L962,
        zoom: settings.DEFAULT_MAP_ZOOM
    }
 }
}
```

- In case we're creating a new empty map, the maplayers array will be empty
- In case we're creating a new map from a layer or just viewing a layer the maplayer will contain that layer

In both case we have  the **center, projection and zoom defaults** will be obtained from the `defaults` property.

@allyoucanmap @afabiani please fill the gaps of this analysis and provide your feedbacks.

**Comment by afabiani** [comment]
@giohappy @italogsfernandes the plan sounds good, just would like to focus the attention on read/write permissions and fields de-hydratation accordingly to the user rights.

I would contextually envisage a set of "sensible" attributes (like the `perms` ad an instance) which should be hidden to RO users (unless used somehow from the client).

Moreover we will need to make a strong security assessment along with test-cases on who can read or write a Map configuration through the APIs.

**Comment by giohappy** [comment]
@afabiani sure, in particular with regards to the Dataset model data returned inside the maplayer object

**Comment by giohappy** [comment]
@italogsfernandes new round of review with @allyoucanmap and the outcompes are promising.

### Map API GET
The objects even simpler then what I said in my previous comment. And this is needed only for existing maps (GET):

```
{
    <what is already returned by the `/api/v2/map/{id}?include[]=data`>,
    "maplayers": [
        {
            id: maplayer.id,
            extra_params: (seem below)
            dataset: {
                (seem below)
            }
            style: (seem below)
        }
    ],
}
```

- **dataset**: only a subset of fields of the Dataset model are required here, i.e. those required by the client as can bee seen here https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/client/js/utils/ResourceUtils.js#L53-L64
- **extra_params**: an opaque JSONField where the client can put useful information about the maplayer. For the moment the only extra information will be the "msid", which is set by the client to match the maplayer with the layer inside the mapconfig blob
- **style**: the style selected for this dataset in this maplayer

The "defaults" that I included before are not needed, since the client already obtain them from the context inside the [_geonode_config.html](https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html#L100-L112) 

Permissions are already provided inside the map object returned by `/api/v2/map/{id}`, so no need to return it again.

In practice the APi should add the maplayers array, which reflect the simplified MapLayer model.
Notice that in this moment the map's maplayers can be retrieved from `/api/v2/map/{id}/datasets`. The name of the endpoint is wrong (it should be `/api/v2/map/{id}/maplayers`), but in any case it's not currently used by the client. The new MapLayer objects will be returned (and set) inlined with the map, so this endpoint can be removed in the future.

### Map API POST/PUT/PATCH
The client is using the /api/v2/map/{id} also to save and update maps. The API currently use the MapStore serializer to read into the map config and permorm the downstream serialization. Once it will be the client to provide the needed information, we can remove the [hooksets ](https://github.com/GeoNode/geonode/blob/7a8f750030a20bc9b8a62cd13c63303163ae6339/geonode/maps/api/views.py#L74-L83) and any [reference to the MapStore serializer](https://github.com/GeoNode/geonode/blob/7a8f750030a20bc9b8a62cd13c63303163ae6339/geonode/maps/api/hook.py#L107-L112) from the maps module 

On save the client will send a partial object as the one returned from the API:

```
{
    <these fields are already set buy the client when posting, putting or patching a map>
    "maplayers": [
        {
            extra_params: (seem below)
            style: (seem below)
        }
    ],
}
```

### Map embed views and templates
Although we're still relying on the geonode urls to trigger the chain for obtaining the embed view, 99,99% of the work done here is not useful anymore. The client, which is instantiated inside the geonode-mapstore-client embed templates, use the api/v2 to obtain the map data and the map config (`/api/v2/map/{id}?include[]=data`). The only info it needs from the context are [the resource id and the resource type](https://github.com/GeoNode/geonode-mapstore-client/blob/d6f8fc72c576b2b62429f9f01669e56c38615ca4/geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html#L48-L49) .
If we move the urls patterns from geonode to the mapstore client, we can remove all the views, templates and mapstore adapters.

### New maps and view layers
This already rely completely on the new APIs and the defaults inside `_geonode_config.html` , so no need to provide default values or whatsoever.
