### ISSUE TITLE
Admin users should be hidden from the share panel

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#464]
@afabiani the admin user should never be included inside the permissions list. There's no reason to manage his/her permissions from the client.

![image](https://user-images.githubusercontent.com/571129/140105673-314d3e6a-e0fc-4b67-806f-c3ec184fb85c.png)

**Comment by afabiani** [comment]
@giohappy it looks to me a client issue.

**Comment by giohappy** [comment]
@afabiani I don't think the client should implement filtering logic in this case. There's no need to return the admin from the backend, since I don't see any case where this could be useful. 

I hope that, even if the client sets the permissions for the admin inside a request, the backend doesn't take them in consideration...

**Comment by afabiani** [comment]
@giohappy the backend forces the superusers' permissions and returns them through the apis. Of course it prevents setting/removing the superusers and owner's permissions, but, at the same time it returns the perms attached to a resource coherently. Therefore I guess that the client should manage this accordingly, maybe by disabling the dropboxes or something. Delegating the backend to remove some perms from the api does not look to me a good solution.

**Comment by giohappy** [comment]
@allyoucanmap opinions? If you prefer this approach ok.

**Comment by allyoucanmap** [comment]
@giohappy @afabiani we could filter out the dropdown for superuser but how can the client guess/know which is an superuser or not?
I don't see a field that tells the client if an entry is a superuser or not. Probably for the default admin we can look at the pk equal to 1000 if this is always true?

![image](https://user-images.githubusercontent.com/19175505/140908677-304147f1-f49e-42ab-844e-171b4a4e2e32.png)

**Comment by afabiani** [comment]
@allyoucanmap I would propose something like the following:

1. Disable the dropodown corresponding to your current `username`
2. Add a flag to the api telling to the client if the user is a superuser or not, in that case the dropoboxes corresponding to those  ones must be disabled

**Comment by allyoucanmap** [comment]
@afabiani 

> 1. Disable the dropodown corresponding to your current username

I think now it's not possible to add the current user anyway we could add an additional check

> 2. Add a flag to the api telling to the client if the user is a superuser or not, in that case the dropoboxes corresponding to those ones must be disabled

ok, with a flag should be easy to hide the dropdown

**Comment by afabiani** [comment]
@giohappy @allyoucanmap the corresponding issue on GeoNode [here](https://github.com/GeoNode/geonode/issues/8361)
PR incoming

**Comment by afabiani** [comment]
PR for the backend part [here](https://github.com/GeoNode/geonode/pull/8363)

For the frontend part please refer to the same issue.
