### ISSUE TITLE
Restore document_metadata_detail and geoapp_metadata_detail

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#466]
These views / templates were dropped with https://github.com/GeoNode/geonode/pull/8201 but they're still needed.
Users without metadata edit permissions can view the metadata detail of a resource. Having removed document_metadata_detail and geoapp_metadata_detail breaks this functionality. Some examples are reported in the following images.

@italogsfernandes Either we revert the PR and create it again without the removal of those views, or they must be restored from previous versions. Do as you prefer.

![image](https://user-images.githubusercontent.com/571129/140165770-44510001-866e-49d5-b7e2-587d92006f3b.png)

![image](https://user-images.githubusercontent.com/571129/140165811-69a5c81f-df87-4a50-a6f6-2a683f2ee715.png)

**Comment by italogsfernandes** [comment]
I will create a PR reverting the deletion of that template.
