### ISSUE TITLE
Bad GFI request

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#470]
@afabiani can you please take a look at [this map](https://master.demo.geonode.org/catalogue/#/dataset/165)?
Proxied GFI requests return a 400 Error, however doing the request directly (not proxied) works fine.

![response error with for GFI](https://user-images.githubusercontent.com/571129/140975624-fee5a77a-8402-432e-ae11-694c21f36ba0.gif)

**Comment by afabiani** [comment]
@giohappy it's working correctly right now... probably the headers injected to the response through the ext PR fixed this one too

![image](https://user-images.githubusercontent.com/1278021/141081912-d6f4e248-8ced-49b8-b2c0-652b6ff94bde.png)
