### ISSUE TITLE
Document metadata detail always redirects anonymous user to login

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#471]
Even if "View" or "Download" are set (inside the Share panel) for Anonymous users, trying to access the page redirects to the login.

**Comment by italogsfernandes** [comment]
After trying to reproduce the error, I could not reproduce the problem in my local machine.
I tried with the current code at master and also with the latest commit before the "[Fixes #8200] Drop legacy views and templates (#8201)" (`git reset --hard da297e687ab445c669978dac316d2b9ea45933ed~1`)

After setting a dataset with the permissions, and going to the metadata_detail page (http://localhost:8000/catalogue/#/dataset/1/metadata_detail), the only call with an error for an Anonymous user was the following:

* call:
```bash
curl 'http://localhost:8000/api/o/v4/userinfo' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Referer: http://localhost:8000/catalogue/'
```
* response:
```json
{
   "errors" : {
      "auth" : [
         "No token provided."
      ]
   },
   "status" : "error",
   "success" : false
}
```

**Comment by giohappy** [comment]
the URL is wrong. Metadata details are served by legacy django views. In your case it is [http://localhost:8000/documents/1/metadata_detail](http://localhost:8000/documents/1/metadata_detail)

**Comment by italogsfernandes** [comment]
## Cause of the problem:
Originally, the `document_metadata_detail` view, had not the "@login_required" decorator. (https://github.com/GeoNode/geonode/pull/8201/files#diff-96764256eb531d02e9a49631daee9396b3fe3fad2f9792bb617f95493f4e8e87L679-L712)
But when reverting the commit the `@login_required` decorator from the `document_remove` view as mistaken added to the `document_metadata_detail` view. (https://github.com/GeoNode/geonode/pull/8201/files#diff-96764256eb531d02e9a49631daee9396b3fe3fad2f9792bb617f95493f4e8e87L653-L654 and https://github.com/GeoNode/geonode/pull/8316/files#diff-96764256eb531d02e9a49631daee9396b3fe3fad2f9792bb617f95493f4e8e87R483-R484)

So a PR simply removing the `login_required` will be created. Just to be sure, I'm also re-verifying `geoapp_metadata_detail` and `map_metadata_detail`.

**Comment by italogsfernandes** [comment]
Issue at geonode repo: https://github.com/GeoNode/geonode/issues/8372
PR at geonode repo: https://github.com/GeoNode/geonode/pull/8373

**Comment by giohappy** [comment]
ok, I guess it was introduced when you rolledback the removal of the embed views, right?

**Comment by italogsfernandes** [comment]
> ok, I guess it was introduced when you rolledback the removal of the embed views, right?

Exactly
