### ISSUE TITLE
Import GeoLimits from shapefile or GeoJSON

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#475]
GeoNode version 3.2.x and 3.3.x have the upload functionality for geolimits that allow the user to add polygon or multipolygon geometry from external shapefile or GeoJSON files.

version 3.2.x and 3.3.x in layer page:
![image](https://user-images.githubusercontent.com/19175505/142181103-10211c16-04ff-46cf-b742-775d563ec0df.png)

GeoNode master branch is not supporting this functionality yet.
This is the expected implementation:

- a new button in the geolimits toolbar will be available for datasets
- user click on the button and the file navigation dialog pop up
- user can select one file (zip for shapefile, json for GeoJSON)
- show a overlay panel inside the can show missing steps to complete the import (EPSG, Encoding) or to show an error
- once successfully complete the new polygon geometries will be added to the current geolimits

New button in the UI:

![image](https://user-images.githubusercontent.com/19175505/142181569-8dba3d16-9a6f-49dc-b6f5-cb454d80b5f6.png)

Success

- autofill the EPSG if it possible to recognize it

request to confirm the EPSG and Encoding
![image](https://user-images.githubusercontent.com/19175505/142185587-0eec1a4b-705c-4118-af2c-c810117453b0.png)

Note we should investigate if the Encoding is needed and how many EPSG we could support client side. If these information can be skipped we could import directly the new polygons

Errors

- file does not contains polygon or multipolygon
- the file is not of type geojson or shapefile
- general error in upload phase
- EPSG not supported

**Comment by giohappy** [comment]
@allyoucanmap I would keep it simple. Datra is expected to be provided in WGS84. We don't care of the encoding, since we're not going to parse the attributes.

**Comment by giohappy** [comment]
closied in favour fo https://github.com/GeoNode/geonode-mapstore-client/issues/833
