### ISSUE TITLE
Improve the owner label inside share panel

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#477]
proposal:
![image](https://user-images.githubusercontent.com/19175505/142212450-79039635-00c4-40ad-b253-7c4aed2aa529.png)

inside panel:
![image](https://user-images.githubusercontent.com/19175505/142212396-0a7903f9-fa3f-4449-b20c-af182c31d0d3.png)

**Comment by giohappy** [comment]
Nice but I think we should harmonize it with the rest. I would try to 

 - make the lable a bit smaller
 - move the label to te right, alinged vertically with the select boxes.

**Comment by allyoucanmap** [comment]
@DavidQuartz tested on master and the translations for owner are missing maybe we lost some pieces while merging

please create a new PR with the missing translations, thanks

![image](https://user-images.githubusercontent.com/19175505/142664784-e6f388ee-8264-4433-93c5-eab33cb1d916.png)
