### ISSUE TITLE
Harvesting session left in a wrong state when run in a sync context

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#479]
I've spent some time debugging the issue  but I wasn't able to spot where the session records_count and total_records_to_prcess get reset to 0 at the end of the harvesting finalization step.

Step debuggin, the session holds the expected values until [finish_asynchronous_session](https://github.com/GeoNode/geonode/blob/032a4e7ea3085d95524b57dfe2861ed85f97505d/geonode/harvesting/tasks.py#L537) but when it reaches [this line](https://github.com/GeoNode/geonode/blob/032a4e7ea3085d95524b57dfe2861ed85f97505d/geonode/harvesting/models.py#L429) it's status is already reset, although not yest committed to the DB.

Notice that the mentioned line is probably wrong in a sync context, since the sessions is given the PENDING state after the task hasr run, and it's never changed afterwards.

@ricardogsilva I would like the system to work both in an async and a sync context. In any case, I want to be sure that we don't have some weak mechanism that might also affect an async context. I wan't able to reproduce this on the dev server lately, but something similar happened also there once, and it's an async env.

**Comment by ricardogsilva** [comment]
As per my latest PR geonode/geonode#8492 I believe the harvesting workflows to be more robust and not being stuck in invalid statuses anymore - Even if such an error may arise, there is also now a django admin action to resert the harvester status. As such, I think we can close this issue
