### ISSUE TITLE
Thumbnail urls are returned as base64 instead of a URL to the static image

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#483]
When thumbnails are uploaded from the client they're sent as base64. The backend, in the case of maps, renders the posted base64 encoding into a file image, which is returned by the API as the `thumbnail_url` property within the resource response. 

The same doesn't happen for the other resource types. When the thumbnail is uploaded from the client editor, the image is saved and returned as base64,

**Comment by marthamareal** [comment]
@giohappyWe could solve this by making GeoApps use the save_thumbail method like other resource types. Eg given the above format of the thumbnail_url, we could pass that url in a function similar to this and then pass the results to save_thumbnail. on creating a geoapp.

**Comment by marthamareal** [comment]
@giohappy since we have [533](https://github.com/geosolutions-it/nexus-geonode/issues/533) merged, Should we proceed with this issue by making the upload form in the client use the new API to solve the issue?

**Comment by giohappy** [comment]
@marthamareal if you refer to the client inside the metadata wizard pages, we have to wait for #546. 
An issue is already linked to this epic for the new client, and it's something that is being addressed by the FE team.

**Comment by marthamareal** [comment]
Tested and thumbnail_urls are returned correctly for all resources.
