### ISSUE TITLE
UI improvements to the toolbars for the editor page

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#490]
Given the following:

 - the title of the resource placed to the far right doesn't stand out (also because of the excessive size of the map search bar!)
 - we would like to have a button to go back to the catalogue page, instead of having to either fo to the home page (clicking the logo) or a specific resource type subset
 - the navigation menu is taking too much space and distracts the user from the more relevant editing toolbar

For all these reasons we want to refactor the layout accoridng to the following mockup, where:

 - hide the bavigation bar. A class will be added by the MapStore client to force the bar hidden
 - reduce the size of the action bar
 - add a compact breadcrumb with a "home" icon linking to the catalogue home (not GeoNode home)
 - insert the resource title, which is cut (with ellipsis) and a title will show the full content
 - an "i" icon will replace the "Info" button

the mockup doesn't diaply it but I would like to test a slighlty different background for the breadcrumb + info icon, to make it appear like a fixed widht back that stands out from the rest of the menu buttons.

![image](https://user-images.githubusercontent.com/571129/143261670-653f6670-755a-4c56-a9f1-92ebd19a39cf.png)

**Comment by DavidQuartz** [comment]
@giohapp does any of these backgrounds work for the breadcrumb and info icon?
1.
![background test](https://user-images.githubusercontent.com/42542676/144207392-2a85fc8e-44d0-44d0-89a1-3a710d1bfed8.png)

2.
![Screenshot 2021-12-01 at 09 35 10](https://user-images.githubusercontent.com/42542676/144209414-c6772119-10ae-4a3a-b00e-78cdd41fcff4.png)

**Comment by giohappy** [comment]
I'd go for the second one @DavidQuartz
