### ISSUE TITLE
Force layer update when the style editor is closed

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#491]
When a style has been edited inside the style editor the client should force the override of the stale cached layer when the style editor is closed, otherwsie the new style is not visible until the page isn't refreshed.

![force layer update](https://user-images.githubusercontent.com/571129/143258013-fd775a0e-b05b-4efd-98c8-7a60ea066e3f.gif)

**Comment by DavidQuartz** [comment]
@giohappy  I am unable to reproduce the issue as the master instance behaves as expected. I suspect it may be a caching issue on the server side. However, I have added a `_v_` parameter in the layers to force cahe drop on the client side.
@allyoucanmap
