### ISSUE TITLE
The ptype is missing from /api/v2/datasets

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#497]
The client uses the `ptype` to understand if a layer is WMS or ArcGIS but this property is not provided in the `/api/v2/datasets` endpoint

eg: https://master.demo.geonode.org/api/v2/datasets

ptype value is only available in /api/v2/datasets/{pk} endpoint

**Comment by giohappy** [comment]
https://github.com/GeoNode/geonode/issues/8427
