### ISSUE TITLE
Issues with responsiveness on card view

### ISSUE THREAD

**Issue by DavidQuartz** [geosolutions-it/nexus-geonode#498]
The layout when viewing resource cards is not fully responsve as seen below:

![Mobile bug](https://user-images.githubusercontent.com/42542676/143420363-16630f4d-7682-4d64-9c85-1682fb7a51da.gif)

There seems to be some conflicting styles causing the severity of this bug to differ depending on where the client navigates from.

**Comment by allyoucanmap** [comment]
Note: this issue seems due to the search bar at the top that does not fit correctly in small screens

**Comment by DavidQuartz** [comment]
> Note: this issue seems due to the search bar at the top that does not fit correctly in small screens

@allyoucanmap I have been investigating the issue and is seems to be caused by a miscalculation of the resource card width among other things. Fixing the making the search bar responsive does not solve the problem.

**Comment by DavidQuartz** [comment]
@allyoucanmap the issue was caused by the parents of the Cards component not having their widths set to 100% of their container. So after some points, the parents width outgrew their containers and the detected width for the cards were supplied based on that, resulting in wrong card widths
