### ISSUE TITLE
Add "Unpublished" filter option

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#502]
It adds to the already available "Pending approval" filter

![image](https://user-images.githubusercontent.com/571129/144044694-8101343a-57a3-4abd-bd0e-fd378b0d2917.png)

**Comment by luorlandini** [comment]
@allyoucanmap @giohappy 
filter Unpublished added, when I tried it, I got this message error: ["Invalid filter field: unpublished"] 
maybe it needs to be added to the BE, I'm proxying to remote master instance

**Comment by luorlandini** [comment]
@giohappy @allyoucanmap 
filter Unpublished added, when I tried it, I got this message error: ["Invalid filter field: unpublished"]
maybe does it need to be added to the BE? I'm proxying to remote master instance

https://master.demo.geonode.org/api/v2/resources?filter{unpublished}=false&page=1&page_size=20&filter{metadata_only}=false

**Comment by giohappy** [comment]
ok @luorlandini let me check

**Comment by giohappy** [comment]
@luorlandini you have to use `is_published=false` (as in `is_approved=false`)

**Comment by luorlandini** [comment]
thanks @giohappy I'm going to change it
