### ISSUE TITLE
GeoNode plugin is showing an empty menu item

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#506]
![image](https://user-images.githubusercontent.com/571129/142906878-f8fe5d5e-7019-4ae9-b7ba-248deb4b9e20.png)

**Comment by ricardogsilva** [comment]
This is being tracked in kartoza/qgis_geonode#180

**Comment by ricardogsilva** [comment]
Fix has been merged, in kartoza/qgis_geonode#196 so we can close this
