### ISSUE TITLE
"Add GeoNode layer" menu item under "Add layers"

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#509]
I guess the API supports adding a quick link to the layers manager, right @ricardogsilva?

![image](https://user-images.githubusercontent.com/571129/144280379-1794f74a-8e1b-424b-b4f0-4cbb84256c02.png)

**Comment by ricardogsilva** [comment]
@giohappy unfortunately QGIS does not allow opening the datasource manager dialog from plugins yet. I reported this in https://github.com/qgis/QGIS/issues/46577 so eventually it may get fixed. It won't be making it in time for the NEXUS release though.

**Comment by ricardogsilva** [comment]
Also tracking this issues in kartoza/qgis_geonode#166, so we can close this one
