### ISSUE TITLE
Height of breadcrumbs changes based on the page

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#515]
The expected height for breadcrumb field is the one we have in dataset page fro example
![image](https://user-images.githubusercontent.com/19175505/145035534-6ad3ef9f-da51-4a02-a3d6-0c11617cef92.png)

other pages that does not have the info panel have a different haight, probably we need a min-height

- /edit/style (dataset)
![image](https://user-images.githubusercontent.com/19175505/145035036-fad8282c-ad4b-481d-b105-2b258f6fdfbd.png)
- /edit/data (dataset)
![image](https://user-images.githubusercontent.com/19175505/145035082-f226cc20-e3c3-4976-992d-51db6c37c775.png)

- /map/new
- /geostory/new
- /dashboard/new
![image](https://user-images.githubusercontent.com/19175505/145035236-438b8c3f-3c7b-47b7-8a04-5addb6a0c40a.png)

Should new pages show only the home? @giohappy

**Comment by allyoucanmap** [comment]
@giohappy should we change also the style and edit page
from:
![image](https://user-images.githubusercontent.com/19175505/145036515-ad1d6617-6f0f-4e74-889d-c17a3b21d87f.png)
to:
![image](https://user-images.githubusercontent.com/19175505/145036443-9d309406-b18e-4f8f-9b27-d11a7916d90b.png)

where we can click on the layer name to go back to the previous page?

**Comment by giohappy** [comment]
@allyoucanmap ihmo the subpages should show Go back to {name} (in case). In any case I would remove the breadcrumb

**Comment by giohappy** [comment]
As a clarification @DavidQuartz  (before closing #516):

 - breadcrumbs will only be visible on the main editor page of existing resources
 - it will hidden from subeditors (style, data, etc.)
 - it will be hidden from new resource pages
