### ISSUE TITLE
When creating a new resource the breadcrumb should be hidden

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#516]
The empty breadcrumb is useless.

![image](https://user-images.githubusercontent.com/571129/145385792-680a1131-c8f1-4907-b0db-6df91fd20a0e.png)

**Comment by DavidQuartz** [comment]
@giohappy this has already been mentioned in this issue [this issue](https://github.com/geosolutions-it/nexus-geonode/issues/515) which I am about to open a PR for.

**Comment by giohappy** [comment]
closing in favour of #515
