### ISSUE TITLE
QGIS dataset style sync

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#517]
### Requirement
Users must be able to view and update the single (default) style assigned to a dataset.

### Rationale of the single style model
Following the change implemented in GeoNode master, only one style can be assigned to a dataset. This follows the logic of datasets being only base resources to be employed in maps and other geoapps. Other platforms don't even let the user style a dataset (e.g., Carto). In GeoNode we still let users change the default style of a dataset, for its preview and to provide a sound default visualization when the dataset is emplyed as a map layer. 

### Acceptance criteria
Depending on the type of service that the user select for vieweing the dataset, the following cases will be implemented:

- **WMS**: the default style is automatically used, no need to select any style. No option to edit the style, being a WMS layer
- **WFS**: the default SLD style is downloaded and converted to QGIS style. **Notice that a CSS style might have been used for the dataset, so the /styles/{style}.sldn extension must be added to force the SLD (con)version when querying the GeoServer styles REST API**. Users can edit the style and sync it back to GeoNode (a warning should be displayed about the limitations of the conversion between QGIS style and SLD). 
- **WCS**: SLD cannot be read by QGIS raster layers, so the default QGIS style will be applied to the raster. A warning will be displayed to explain this limitation. Users can edit the style and sync it with GeoNode.

**Comment by ricardogsilva** [comment]
This has been implemented in kartoza/qgis_geonode#185
