### ISSUE TITLE
Extend the upload API to accept compact permissions

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#520]
The upload page is going to be replaced by a new client based page. The refactoring will include replacing the legacy permissions panel with the new compact permissions (as within the share panel). 
For this reason we need to implement the support for compact permissions inside the current Upload API. 

Ideally we should replace the current upload API with the new one provided by the Resource Manager, but it will be a much more time consuming task. So for the moment we will just extend the current Upload API.

**Comment by afabiani** [comment]
@giohappy 

Please check the issue [#8522](https://github.com/GeoNode/geonode/issues/8522) for the technical proposal and the associated upstream PR [here](https://github.com/GeoNode/geonode/pull/8523)
