### ISSUE TITLE
Reorder actionbar menu items

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#526]
All resource types:
- Save
- Edit
- Share
- Delete

Resource specific actions (after the vertical separator)
- Dataset
  - Print
  - Measure
  - Export
  - Create map
- Map
  - Print
  - Measure
  - Annotations
  - Add Layer

**Comment by DavidQuartz** [comment]
Should Annotations in Map come after Add Layer? @giohappy 
![Screenshot 2022-01-13 at 09 11 49](https://user-images.githubusercontent.com/42542676/149300407-322dcd91-bf4f-42dc-8ce6-5e336716602d.png)

**Comment by giohappy** [comment]
@DavidQuartz see the updated bullet list.
