### ISSUE TITLE
Improve icon buttons for setting resource thumbnail

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#529]
Let's remove the opacity for the thumbnail buttons and make them squared (with sligh border radious as the rest of the UI). They are not visible enough, and removing thethe opacity we make give them the same style as the hover menu inside the home cards.

Notice that the mockup image shows an Apply button that will be addressed in another issue

![image](https://user-images.githubusercontent.com/571129/146909152-f58b3f7a-1bef-458a-90d0-4bc723a08842.png)

**Comment by DavidQuartz** [comment]
@giohappy is this ok?
![Screenshot 2022-01-20 at 12 48 03](https://user-images.githubusercontent.com/42542676/150341604-0b1bca44-c38b-4107-9ba6-1cca175b08aa.png)

**Comment by giohappy** [comment]
yes @DavidQuartz
