### ISSUE TITLE
Info Panel layout enhancements

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#531]
![image](https://user-images.githubusercontent.com/571129/146910996-24094087-bf14-45ef-8e68-0fcb14c90733.png)

**Comment by giohappy** [comment]
@DavidQuartz regarding the tabs, let's keep the Tabs structure (although we remove the "Attributes" tab). We will use the tabs layout to include (in the future):

- a new "Datasets" tab for maps, with the list of the datasets referenced by the map
- a new "Maps" tab for datasets, with the list of maps where this dataset is used

**Comment by DavidQuartz** [comment]
@giohappy is this okay?
![Screenshot 2022-01-13 at 10 52 34](https://user-images.githubusercontent.com/42542676/149316958-bf6173a4-b356-417f-a221-ddf6bf5e4c3b.png)

**Comment by giohappy** [comment]
I would give the title a bit more relevance, maybe increasing font-size to 1.1em, both in the info and the preview panel.

![image](https://user-images.githubusercontent.com/571129/149318257-7c68adf1-3b73-4ea1-88b1-65147acd3ab2.png)

**Comment by DavidQuartz** [comment]
@giohappy is this okay?
- title 1.4rem
 - username / date 0.8rem
 - description 0.8rrem
 - increased spacing between username and description
 
![Screenshot 2022-01-13 at 15 36 43](https://user-images.githubusercontent.com/42542676/149360802-740ed3b0-9030-41b2-bd72-f89ae24454d9.png)

**Comment by giohappy** [comment]
looks good to me know
