### ISSUE TITLE
Fixes for mobile

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#538]
- [x] #556
- [x] https://github.com/geosolutions-it/nexus-geonode/issues/498 Fix search bar
- [x] https://github.com/geosolutions-it/nexus-geonode/issues/559

**Comment by DavidQuartz** [comment]
After going through geonode mapstore client on mobile, I made the following notes and observations in addition to the summary found here under mobile layout here https://docs.google.com/document/d/1evvXb4bqw2SS-pw9qe_KaA-zE9toQulxKVn7KWnEABI/edit
# Notes on responsiveness
### Home Screen
- The search bar is not responsive, possibly affecting the rest of the page. This also makes sign in impossible
- The header needs some adjustment to fix some responsivity issues as shown below:

<img src="https://user-images.githubusercontent.com/42542676/149509507-b03bc2ab-8ff6-48fd-9d2a-6f3464603e5c.png" alt="header" width="300px"> <img src="https://user-images.githubusercontent.com/42542676/149508965-f3de0ae6-0a23-4538-97a2-8621fe73bb81.png" alt="header" width="335px">

- The resource cards seem to have conflicting styles causing them to become unresponsive in some cases. This adds an x-axis scroll to the page
- Details panel is not responsive in some cases. Also the texts need adjustment

![Screenshot 2022-01-14 at 11 11 47](https://user-images.githubusercontent.com/42542676/149509584-ab5c2189-bf75-4486-98fd-49c35daee645.png)



### Catalogue Page
- Filters section needs responsive adjustments

![Screenshot 2022-01-14 at 09 51 37](https://user-images.githubusercontent.com/42542676/149512528-ff7614bc-f874-4a38-9ef1-5fdb7379dcf8.png)

![Screenshot 2022-01-14 at 10 40 08](https://user-images.githubusercontent.com/42542676/149512612-74e206e8-5d5a-4296-aeb5-6e3f3749f890.png)

- Remove ‘Add Resource’ button
- In some cases, resource card is completely out of shape

![Username filter](https://user-images.githubusercontent.com/42542676/149512683-20b1ba8b-3810-48c7-aced-c87e78d5966d.gif)



### Resource View
- Action navbar is not responsive so we are unable to see fullscreen plugin. The search bar also goes behind Legend plugin in Dataset view. We should move the searchbar lower when opened on mobile

![Screenshot 2022-01-14 at 10 35 20](https://user-images.githubusercontent.com/42542676/149516288-a17dec1b-8b24-4731-9549-e426226a121e.png)

- Action Navbar is in a confused state in the Geostory and Dashboard views as seen below. (On screen widths below 522px)

![action navbar confusion](https://user-images.githubusercontent.com/42542676/149512924-8e3f50b5-4a9a-458f-b532-d51b321a383a.gif)

- Burger menu may have to have a fixed position on the right corner next to fullscreen view in mobile view and menu content would be displayed to the left in that case

- Share panel and info panel are not responsive

- Alerts in view metadata page not responsive



# Notes on Features fixes

Dataset View
We should remove the following:
- Create map
- All edit functionality
- All save functionality

Document View
- PDF resources does not seem to load on mobile

Map View
We should remove the following:
- Add layer
- Annotations
- All edit functionality
- All save functionality

Geostory and Dashboard views
We should remove the following
- All edit functionality

**Comment by giohappy** [comment]
@DavidQuartz do you confirm the estimate from @allyoucanmap ?

**Comment by DavidQuartz** [comment]
> @DavidQuartz do you confirm the estimate from @allyoucanmap ?

Yes I do
