### ISSUE TITLE
Thumbnails management enhancements

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#540]
- [x] https://github.com/geosolutions-it/nexus-geonode/issues/547
- [x] #529 
- [x] https://github.com/geosolutions-it/nexus-geonode/issues/542
- [x] #555

**Comment by DavidQuartz** [comment]
@giohappy is there a related issue for the last task? It's not immediately clear what is required.

**Comment by giohappy** [comment]
@DavidQuartz issue created. @allyoucanmap can assist you on it.
