### ISSUE TITLE
module "typing" has no attribute "Final"

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#544]
Trying to install the plugin on QGIS 3.18.0 from the OSgeo4W installer throws the following error

![image](https://user-images.githubusercontent.com/571129/149327661-30edbc0f-af38-4b7a-9a33-dc60c8009d67.png)

Osgeo4W ships Python 3.7.0 for QGIS 3.18.0 and, If I'm not wrong, the final attribut [was added](https://www.python.org/dev/peps/pep-0591/) only in Python 3.8.
I see online several ways are available to manage the lack of final attribute in previous Python versions.

**Comment by ricardogsilva** [comment]
Hmm, I must admit I did not really test Python3.7. I'll just remove the `Final` annotation then
