### ISSUE TITLE
Failed connection to master demo

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#545]
The connection test with master demo (https://master.demo.geonode.org/) fails. Apparently the plugin sends a request to https://master.demo.geonode.org/api/layers/, which fails because the endpoint was renamed to https://master.demo.geonode.org/api/datasets. 
We didn't consider too much the effect of the renaming since the plan is to deprecate, and finally, remove, the legacy API from GeoNode 4. 

The point is, why are you relying on the legacy API? I suppose it's for GN 3.2.x, but in that case the lack of the API should be managed, since I expect for GN >= 3.3.x only API v2 will be used by the plugin, isn't it?

![image](https://user-images.githubusercontent.com/571129/149328276-1a8d6ccb-9ba7-4421-b8df-be7f56003ca7.png)

**Comment by ricardogsilva** [comment]
@giohappy 
From the screenshot above it looks like you are trying to use the native QGIS GeoNode provider instead of the plugin. Is it so?

AFAICT the plugin is able to connect to `master.demo.geonode.org` without any problem.

**Comment by giohappy** [comment]
shame on me @ricardogsilva. I thought the plugin was installed, despite the error about the Final typing attribute, and I picked the native provider thinking it was the plugin.

Is the native provider going to remain in QGIS? IMHO it should be removed from core, also considering that probably it only works with very old GeoNode versions...
