### ISSUE TITLE
Drop CuratedThumbnail and fix the metadata wizard thumbnail widget

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#546]
CuratedThumbnail is a concept that we're not using anymore. The new API (https://github.com/GeoNode/geonode/issues/8561) for setting thumbnails, and the resource manager, directly set the thumbnail (and the corresponding link) directly, without creating a curated thumbnail object. 

We want to 

 - remove CuratedThumbnail model (and its admin classes)
 - make the metadata wizard page widget use the new /resources/{pk}/set_thumbnail API (with form-data file upload)
 - drop [thumbnail_upload](https://github.com/GeoNode/geonode/blob/eafaf522af073bf183d45880c59a9e0907710416/geonode/base/views.py#L222) view
 - drop CuratedThumbnailForm

**NOTICE**: the migration must take care of the existing curated thumbnails. When needed the resource thumbnail_url and link must be updated, and the image files must be moved out of the "curated" folder

**Comment by marthamareal** [comment]
> **NOTICE**: the migration must take care of the existing curated thumbnails. When needed the resource thumbnail_url and link must be updated, and the image files must be moved out of the "curated" folder

@giohappy Do you mean having a management script that will
- filter resources with curated thumbnails then save those curated thumbnails in the `uploaded/thumbs` folder?
- update the thumbnail Link,
- Then clear the `CACHE/images/curated_thumbs` folder?

**Comment by giohappy** [comment]
yes @marthamareal

**Comment by marthamareal** [comment]
@giohappy Don't we need a separate issue for this command? Because we can not retrieve the curated thumbs from the same PR where we are removing the model.

**Comment by giohappy** [comment]
@marthamareal can't you do it inside a migration with a PythonRun? The goal is to migrate curated thumbnails, both as data and image files. I suppose it can be done inside a migration, without a direct reference to the python class, cant'it? We did something similar in the past. Look at [this](https://github.com/GeoNode/geonode/blob/aed021f4cd0431789bab01ba7ba73c31181852cb/geonode/maps/migrations/0031_auto_20210615_0717.py#L12) for example
