### ISSUE TITLE
Restore Upload metadata and style pages for datasets

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#548]
Two new items under the Edit menu for datasets will link to the legacy pages:

- Metadata upload: /datasets/{alternate}/metadata_upload
- Style upload: https://development.demo.geonode.org/datasets/{alternate}/style_upload

![image](https://user-images.githubusercontent.com/571129/149548027-7cbb8417-1add-4f94-b963-db229f46080e.png)

**Comment by DavidQuartz** [comment]
@giohappy would you also prefer the same arrangement for the Edit as shown in the screenshot?

**Comment by giohappy** [comment]
yes @DavidQuartz

**Comment by giohappy** [comment]
@DavidQuartz the link the description points to development demo. Of course here we meant master demo.
An example: https://master.demo.geonode.org/datasets/geonode:my_layer_st/style_upload
Notice that you need to be logged in to see it.
