### ISSUE TITLE
Change labels for not published and not approved resources

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#551]
I see that the term "Unpublish" has been for not published resources, which is wrong since it looks like a verb for an action.
The terms must be changes to "unpublished", and "not approved", as we have on 3.3.x.
I would also give it less relevance, either completely removing the background and border, as in the following example (use a simple label instead of a button), or make it as in 3.3.x, of course without that spacing (see below)

![image](https://user-images.githubusercontent.com/571129/150095169-5bd2464f-0dee-4522-ba07-bd97bb3172f7.png)

![image](https://user-images.githubusercontent.com/571129/150095236-e3edcc37-d7fa-49f9-9bc7-921193aa43d2.png)

**Comment by DavidQuartz** [comment]
@giohappy when a resource is both unapproved and unpublished, the 2 labels currently appear side by side with their new style as shown below

![Screenshot 2022-01-19 at 16 58 09](https://user-images.githubusercontent.com/42542676/150178254-dc8129cd-d3b2-450a-975a-cf47729ce89d.png)

Is this okay?

**Comment by giohappy** [comment]
Can we separate them with a "-"?

**Comment by DavidQuartz** [comment]
@giohappy like this?

![Screenshot 2022-01-19 at 17 04 36](https://user-images.githubusercontent.com/42542676/150179140-ceaeda7e-d767-4864-ac8b-6183ed5d7110.png)
