### ISSUE TITLE
TypeError: tostring() got an unexpected keyword argument 'xml_declaration'

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#554]
The error was raised while I was trying to upload a style from a raster layer (WCS).

`xml_declaration` was added in Python 3.8. 
See the differences in the doc for [3.7](https://docs.python.org/3.7/library/xml.etree.elementtree.html#xml.etree.ElementTree.tostring) and [3.8](https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.tostring)

![image](https://user-images.githubusercontent.com/571129/150147046-f5134f2f-578d-4469-abfe-2b398d50c2ca.png)

**Comment by ricardogsilva** [comment]
This has been fixed in version `0.9.3` of the plugin, which I just released:

https://github.com/kartoza/qgis_geonode/releases/tag/v0.9.3

I submitted to official QGIs repo, now we need to wait for one of the curators to approve it
