### ISSUE TITLE
Truncate UNPUBLISHED - NOT APPROVED labels

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#559]
Some translations make the lables larger then the available width on mobile.
We want to truncate the labels (with ellipsis) rathen then wrapping to new line.

![image](https://user-images.githubusercontent.com/571129/150773500-08b30502-9412-4069-a160-a6083caf070c.png)

**Comment by DavidQuartz** [comment]
@giohappy it seems this issue has been address by the new resource status label icons https://github.com/GeoNode/geonode-mapstore-client/pull/745

**Comment by giohappy** [comment]
I agree @DavidQuartz. I will close this.
