### ISSUE TITLE
Adopt Basic Auth in QGIS Plugin

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#563]
Oauth2 authentication in QGIS is too complicated for end users, and it requires configuring and sharing configirations secrets for a dedicates QGIS Oauth2 application in GeoNode.

A way simpler solution is to adopt Basic Auth. It's a matter of proxying through GeoNode's own proxy the requests targeting Geoserver.

This means replacing the 
`/geoserver/(ogc)` and `/geoserver/rest/workspace` endpoints with `/gs/ows` and `/gs/rest/workspace `. 

API v2 also support Basic Auth requests. 

In the future we might consider to port Geoserver Basic Auth authentication witg external services in GeoNode. This will permit to make direct basic auth requests to Goeserver, backed by GeoNode authn service.

**Comment by ricardogsilva** [comment]
@giohappy when was the `/gs/<...>` proxy URL introduced?

Is it available for GeoNode version 3.3.x too?

**Comment by ricardogsilva** [comment]
@giohappy 

Upon further testing, it seems that modifying a dataset's style when using Basic Auth (and the corresponding URL, which is of the form <http://localhost/gs/rest/workspaces/geonode/styles/thetest.sld> fails with `HTTP 401 - Host requires authentication`. Note that the request does correctly include the `Authorization: Basic <encoded-auth` header.

Using Basic Auth I seem to be able to:

- Load datasets onto QGIS
- Modify their title and abstract, saving it back to GeoNode

Not being able to modify the symbology seems like a deal breaker though.

**Comment by ricardogsilva** [comment]
For reference, this is being tracked in kartoza/qgis_geonode#222

and my current work is present as a draft PR in kartoza/qgis_geonode#223

**Comment by giohappy** [comment]
@ricardogsilva we have spot where basic auth support must be extended to allow style changes. It should be a quick change in GeoNode, and it should land on master and 3.3.x quickly: https://github.com/GeoNode/geonode/issues/8760

**Comment by afabiani** [comment]
PR merged and backported on 3.3.x and 3.2.x

**Comment by ricardogsilva** [comment]
This is now implemented and has been included in version 0.9.4 of the plugin. I think we can close this issue
