### ISSUE TITLE
Configure version 1.1.0 for WFS layers

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#573]
Given [this issue](https://github.com/qgis/QGIS/issues/47254) with QGIS I suggest to force the configuration to 1.1.0 for the WFS layers. Geoserver supports it and it will grant that edits won't break the geometries.

I suppose it-s a matter of setting it [here](https://github.com/kartoza/qgis_geonode/blob/main/src/qgis_geonode/gui/search_result_widget.py#L397)

**Comment by ricardogsilva** [comment]
working on it, should be ready soon

**Comment by ricardogsilva** [comment]
This is now implemented and has been included in version 0.9.5 of the plugin. I think we can close this issue
