### ISSUE TITLE
GeoNode connection stuck in an inconsitent state if the first connection request goes wrong

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#579]
I've faced this error several times. If the test connection or search functions do not obtain a valid response the plugin / layer manager remains stuck in a status where no further action is permitted or, if permitted, it throws the following exception.
Even closing and reopening QGIS doesn't fix the wrong status. A new connection must be configured from scratch.

If a network error happens during the initial configuration the connection status should be reset to let the user retry.

This can be replicated when the GeoNode instance is not available or when it returns a 50x error (for example it happens when a new deployment of a demo instance is running).

![image](https://user-images.githubusercontent.com/571129/154694426-1394bcf5-9298-460e-9a90-cdb14017c351.png)

**Comment by ricardogsilva** [comment]
@giohappy I've merged kartoza/qgis_geonode#239, which I think is related to this and hopefully fixes it too. Please verify if the problem persists and let me know

**Comment by giohappy** [comment]
Loos good @ricardogsilva
