### ISSUE TITLE
Transfer of raster datasets from dev server to production

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#589]
The size of the raster data uploaded onto the dev server makes their transfer with the harvester time-consuming and heavy for the origin server (because of the adoption of WCS for the transfer by the harvester).

These datasets must be transferred to production and configured manually.

**Comment by afabiani** [comment]
@giohappy almost all the raster must be imported manually unfortunately. Those are more or less 169 datasets.

**Comment by giohappy** [comment]
@afabiani what do you mean with broken? Broken on dev, broken on prod...
