### ISSUE TITLE
Add the possibility to enable or disable dynamically plugins in the TOC toolbar based on permission of the layers

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#59]
We should improve the behaviour of availabilty of plugins in geonode-mapstore-client based on the implementation provided by this issue on MapStore https://github.com/geosolutions-it/MapStore2/issues/6680.

The geonode-mapstore-client should rely also on layer parmission to decide if a plugins should be available for a user.

**Comment by giohappy** [comment]
Close as per this comment https://github.com/geosolutions-it/MapStore2/issues/6680#issuecomment-859447332
