### ISSUE TITLE
Upgrade production instance 

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#594]
- GeoNode 4.0.1 (as soon as it's released)
- Geoserver 2.20.5, so to include the fix to the WPS export and the removal of the INSPIRE plugin.

**Comment by afabiani** [comment]
SPC nexus has been upgraded to GeoNode v.4.0.0 / GeoServer v.2.20.5
instructions documented here
https://docs.google.com/document/d/1NTeugJEiqyM1-tarcrbj6lR6-aHKwnYZ/edit#

**Comment by simboss** [comment]
@afabiani as @giohappy pointed out above the plan was to upgrade **after** 4.0.1 was released not before.
This means we will have to do it again.

Please, follow instructions.

**Comment by afabiani** [comment]
@simboss I was explicitly asked to upgrade it before. Please, better coordinate with PMs next time.

Upgraded to 4.0.1, instructions updated [here](https://docs.google.com/document/d/1NTeugJEiqyM1-tarcrbj6lR6-aHKwnYZ/edit#).
