### ISSUE TITLE
Implement harvester configuration

### ISSUE THREAD

**Issue by ricardogsilva** [geosolutions-it/nexus-geonode#78]
Harvesting shall be implemented in such a way as to allow configuration at runtime.

Configuration shall have two parts:

1. Static configuration - This shall be done in the geonode settings file.
    
    This configuration is about setting the harvester classes that shall be usable at runtime. It shall be optional, a set of standard harvester types must be available, even if not specified. This is mainly to give the GeoNode admins the option to add custom harvester types on a per-deployment basis. For the initial implementation. Example:

    ```python
   # settings.py
   HARVESTER_CLASSES = (
       "geonode.harvesting.GeoNodeHarvester",
   )
    ```

2. Dynamic configuration - This shall be done at runtime by both:

    - Using the django admin
    - Using the GeoNode API

    This configuration shall allow a user to create and modify the configuration of harvesters. Relevant configuration parameters:

    - harvester `type`, which shall be one of the available types, as configured in the static configuration mentioned above
 
    - `enabled`, which shall allow enabling/disabling a harvester

    - `remote URL`, the main URL of the remote service that is to be harvested

    - harvest `frequency`, which shall be the time interval that passes between two consecutive harvesting sessions. This shall be used by the harvest scheduler to keep track of when to trigger new harvesting sessions

    - harvested resources `ownership` - Each harvested resource shall be assigned an owner in the local GeoNode instance. This shall default to the user that is creating the harvester

    - harvested resources `publication status` - Each harvested resource shall be given a predefined visibility in order to control if it becomes immediately public, only available for selected groups or completely private

    - Each harvester type shall also provide its own set of settings. For example:

      - Whether to also harvest the concrete data instead of just the metadata
      - Authentication credentials on the remote server
      - etc.

    As mentioned above, the dynamic configuration must be available via the GeoNode API, in order to allow frontend clients to use it.

**Comment by ricardogsilva** [comment]
I am finalizing a PR for main GeoNode to address this: geonode/geonode#7317

**Comment by giohappy** [comment]
@ricardogsilva so you're assuming that the options will be global for each harvester type, not per remote source,, right?

**Comment by giohappy** [comment]
@ricardogsilva I don't see any issue with a global plan for the harvester so I'm asking here. How do you plan to integrate / replace the current remote services module?
