### ISSUE TITLE
GeoNode API V2 - Layers response is missing properties needed for the MapStore layer configuration

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#80]
A MapStore wms layer configuration needs following properties:

```js
{
    id: , // generated by the client
    type: 'wms',
    name: '...', // name used in the wms request with the properties layer, this name must be composed with workspace:layerName if the workspace is not specified in the url 
    url: '...', // url to the wms service
    format: '...', // format of the wms response eg: image/png
    search: {
        type: 'wfs',
        url: '' // url to the WFS service to use attribute table
    },
    bbox: { bounds, crs }, // layer bbox
    featureInfo: {
        format: 'TEMPLATE',
        template: '' // template for the get feature info if available
    },
    style: '', // if empty use default style
    title: '', // layer title
    visibility: true
}
```

Now it's not possible to generate a complete configuration from the api because are missing following properties:

- url for the WMS request
- url for the WFS request
- the complete name of the layer to use in the request to WMS or WFS
- the format or the available formats for the WMS request

Currently there are also some inconsistencies between the remote and local layers:

- in the dataStore layers the workspace matches with the one used in geoserver so can be used to generate the complete layer name
![image](https://user-images.githubusercontent.com/19175505/114898649-99b04c80-9e12-11eb-8f40-5f3165187d64.png)
- in the remoteStore layers the workspace cannot be used to generate the complete name of the layer
![image](https://user-images.githubusercontent.com/19175505/114898734-aaf95900-9e12-11eb-82b8-1771832d5711.png)

The api should return all the information without adding static constant or logic client side to create a correct layer request.
This should be avoided:

Current test with the new client and API V2 where gnLayer is the response object
![image](https://user-images.githubusercontent.com/19175505/114899436-3f63bb80-9e13-11eb-9bba-e6e8379d5a4c.png)

**Comment by allyoucanmap** [comment]
connected to issue #22

**Comment by giohappy** [comment]
@allyoucanmap can you please clarify which configurations you're talking about? The ones for the layers inside the map configuration inside __GEONODE_CONFIG__, the ones returned from API v2 or both?

I cant' find the json snippets you reported above neither inside GEONODE_CONFIG nor inside the API. For example, this is what I see inside the GEONODE_CONFIG:

**Comment by allyoucanmap** [comment]
@giohappy 

> @allyoucanmap can you please clarify which configurations you're talking about? The ones for the layers inside the map configuration inside GEONODE_CONFIG, the ones returned from API v2 or both?

I'm talking about the API v2. There are not information about the map services in the API v2 so it's not possible to create a WMS request or WFS request. The client needs to get at minimum these information so it does not need to guess the urls or names for the layer:

- url for the WMS request
- url for the WFS request
- the complete name of the layer to use in the request to WMS or WFS
- the format or the available formats for the WMS request

> I cant' find the json snippets you reported above neither inside GEONODE_CONFIG nor inside the API. For example, this is what I see inside the GEONODE_CONFIG:

the screenshot shows the current placeholder on the master branch where the client is trying to create a valid configuration of layer for MapStore. https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/client/js/epics/gnviewer.js#L62-L84 . The

**Comment by giohappy** [comment]
@allyoucanmap what do you expect to receive as WMS and WFS urls? The base URL for Geoserver?

**Comment by giohappy** [comment]
API v2 response for datasets (either from resources/ endpoint or layers/ endpoint) must include the OGC links, as the legacy API does.
An addition to the legacy API should be the inclusion of the layer name / typename, instead of making the client guess it from the resource properties (alternate or whatever).

**Comment by mattiagiupponi** [comment]
https://github.com/geosolutions-it/geonode/pull/854
