### ISSUE TITLE
Define add_resourcebase permission for users

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#84]
GeoNode assumes that any registered user can create new resources. This assumption is reflected in no controls over this permission neither when resource creation is performed anywhere in the code base, nor in the UI. 

In fact, the only case where we needed to hide the creation buttons and forbid resource creation was the `READ_ONLY` mode. Instead of adopting a pemissions check, the solution in that case have been implemented as a check on the `READ_ONLY` settings. Not the best approach indeed, but at least now it will help a to track all the positions where this will need to be changed.

The idea is to use the `add_resourcebase` Django permission (here we don't need Guardian since its not object specific). This permission will be set for any user by default, in order to maintain the current logic, but when returning the permissions for the user we can filter it out for specific conditions, for example when the instance is in `READ_ONLY` mode.

As an example, when this permission will be returned inside the `perms` property of the `users/` and `users/{pk}` response (#83), MapStore client will decide if the "Save As" button (or the Create resource button in the upcoming GeoNode version) should be visible. In case `READ_ONLY` mode is active, the permission won't be returned, and the button won't be visible.

This new permission must be backported to `3.2.x`.

NOTE: apparently add_resourcebase is already available for geostories. It is returned inside the __GEONODE_CONFIG_permissionsList. @marthamareal please investigate wghy.

[https://master.demo.geonode.org/apps/1135/edit#/](https://master.demo.geonode.org/apps/1135/edit#/)
![image](https://user-images.githubusercontent.com/571129/115024500-7512ae00-9ec0-11eb-986f-aee76b784784.png)

**Comment by marthamareal** [comment]
@giohappy  `add_resourcebase` is already available for geostories because the views used [geoapp_detail](https://github.com/GeoNode/geonode/blob/master/geonode/geoapps/views.py#L170) and [geoapp_edit](https://github.com/GeoNode/geonode/blob/master/geonode/geoapps/views.py#L241) have `perms_list` in the config which is used to set the `permisionsList`.

**Comment by giohappy** [comment]
I see @marthamareal. The point is that, even if permissionsList was populated for layers and maps, I suspect the `add_resourcebase` wouldn't probably be returned.

Questions:

 - why is `add_resourcebase` returned inside permissionsList but not inside `/get_perms` (and the upcoming `/perms`) response for a geostory? Ex. https://master.demo.geonode.org/api/v2/resources/425/get_perms. I guess the answer is that the returned permissions are limited to the list set to `VIEW_PERMISSIONS + ADMIN_PERMISSIONS + LAYER_ADMIN_PERMISSIONS`. If that's the case we should add `add_resourcebase` to a new list. Could it be `CREATE_PERMISSIONS` maybe?
 - from what you report I expect to see `add_resourcebase` returned inside layer's and map's permissionList (if they were set correctly?, right?

The general rule is that permissionsList should return the same list as perms/ and get_perms/, including `add_resourcebase`

**Comment by marthamareal** [comment]
> * why is `add_resourcebase` returned inside permissionsList but not inside `/get_perms` (and the upcoming `/perms`) response for a geostory? Ex. https://master.demo.geonode.org/api/v2/resources/425/get_perms. I guess the answer is that the returned permissions are limited to the list set to `VIEW_PERMISSIONS + ADMIN_PERMISSIONS + LAYER_ADMIN_PERMISSIONS`. If that's the case we should add `add_resourcebase` to a new list. Could it be `CREATE_PERMISSIONS` maybe?

True, the `/get_perms` api uses `get_all_level_info` with only the above list.

> * from what you report I expect to see `add_resourcebase` returned inside layer's and map's permissionList (if they were set correctly?, right?

Yes

**Comment by giohappy** [comment]
To clarify @marthamareal:

 - `get_perms/`, `perms` property inside resource response and permissionsList should all return the same [restricted set of permissions](https://github.com/GeoNode/geonode/blob/cd4843236c962904f97c31c9a42da1bbd13202ce/geonode/security/models.py#L399). Probably the views should use [get_user_perms](https://github.com/GeoNode/geonode/blob/cd4843236c962904f97c31c9a42da1bbd13202ce/geonode/security/models.py#L394) instead of django guardian [get_perms](https://github.com/GeoNode/geonode/blob/master/geonode/geoapps/views.py#L212). This is because it doesn't make sense to return `add_resourcebase` within the permissions for a specific resource, since this permission is not linked to a resource, it's a general permission for the user.
 - `add_resourcebase` wil be returned inside the `perms` property of users response. In the future other "global" user permissions will be included (eg. permission to create a user, to create a group, to manage the harvester, etc.)

**Comment by giohappy** [comment]
As agreed with @afabiani the idea is to use Django Groups to manage the set of global permissions to be assigned to users. Basically using the Group concept to define roles.

PLEASE NOTE that here we're talking about Django Groups not the (confusing!) GeoNode GroupProfile. 

The steps are:

- a `contributors` Django group is created by default at install time, and the "base_addresourcebase" permission is assigned to it. The creation of this group could follow the same apporach that [we're using](https://github.com/GeoNode/geonode/blob/cd4843236c962904f97c31c9a42da1bbd13202ce/geonode/people/signals.py#L132) to create (and assign) a user to the "anonymous" group, i.e. it's created the very first time we need it. What do you think @afabiani?
- Every user will be assigned, by default, to the contributors group
- the get_user_perms method will check if **ANY** group associated to the user has the "add_resourcebase" permission assigned. For the moment the only group is "contributors" but this leaves the option to create create additional roles with that permission.

**Comment by afabiani** [comment]
@giohappy yeps, agree with yout statements.

@marthamareal you might need to re-enable the "Group" admin interface from [here](https://github.com/GeoNode/geonode/blob/master/geonode/groups/admin.py#L47). That was hidden in order to avoid users to play with it, but by re-introducing the concept of Django Group that will be needed.

**Comment by giohappy** [comment]
Answering some doubts from @marthamareal:

> 1. Should we assign admin to contributors group?

I don't think it's needed. The control logic for admins uses the "admin" flag of the user model. The day we will decide to manage admin permissions through roles, a dedicated group will be created.

2. Should we assign anonymous user to contributors group?

Definetely no! Anonymnous users are not contributors :) They can't create resources.

3. For now are we only returning the new `base_addresourcebase`(assigned to contributors group)` in perms for apis `/users` and `/users/{pk}

See my edit at point 3 in my previous comment. We will return the whole set of permissions, which is the union of the groups permissions from the groups the user is a member of.

**Comment by giohappy** [comment]
Issue created upstream https://github.com/GeoNode/geonode/issues/7355

**Comment by giohappy** [comment]
As agreed the `People.perms` property will returned the mapped namings for the permissions:

`base_addresourcebase -> ADD_RESOURCE`

Similar mappgin will be adopted along the way to convert all the GeoNode code to use stable constanst instead of the original Django / Guardian permission strings. This will also decouple the client code from the Django permissions naming (which would change if the module or the model that implementes them changes).
