### ISSUE TITLE
Client - Implement DetailViewer plugin

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#92]
We should implement a Detail viewer plugin to display information about the resources. The initial expcted information will be:

- Thumbnail: if the user has permission it should be able to uplaod and change the thumbnail. A pencil icon should be visible over the thumbnail in case of edit permission.
- Title: if the user has permission it should be able to edit the title inline. A pencil icon should be visible near the title in case of edit permission.
- Author
- Creation Date
- Description: if the user has permission it should be able to edit the title inline. A pencil icon should be visible near the title in case of edit permission.
- Categories

We should use the existing component currently available in the detail route.

The plugin should export two component rendered in two different container:
- DetailPanel rendered in the ViewerLayout with target rightColumn
- The DatailPanel toggle button rendered as item in the ActionNavbar

example of export targeting different containers:

```js
// this plugin will be avilable inside the items prop of the targeted container with grater priority 
export default createPlugin('DetailViewer', {
    component: DetailViewerPlugin,
    containers: {
        ViewerLayout: {
            name: 'DetailViewer',
            target: 'rightColumn',
            priority: 1
        },
        ActionNavbar: {
            name: 'DetailViewerMenuItem',
            target: 'dropdown.edit', // we should find a way to target an existing dropdown
            Tool: DetailViewerMenuItem, // The toggle button
            priority: 1
        }
    },
    epics: {},
    reducers: {}
});
```

![image](https://user-images.githubusercontent.com/19175505/115041904-4a7e2080-9ed3-11eb-8d78-a7f0a6951765.png)

**Important**: This plugin/component is shared on all routes of the applications

**Comment by luorlandini** [comment]
@giohappy  @allyoucanmap 

about the abstract edit, has the user the possibility to use a wysiwyg editor, to format text, color etc ..?

**Comment by giohappy** [comment]
@luorlandini if we can implement a simple wysiwyg editor (even simpler then the one currently adopted inside the metadata edit pages) it would be nice.

**Comment by luorlandini** [comment]
@giohappy @allyoucanmap 

Could we implement a button, to switch in edit mode, and 2 to confirm or cancel the user changes?
For example at the bottom of the detail viewer

**Comment by allyoucanmap** [comment]
@luorlandini @giohappy
I would avoid to add steps to confirm or cancel because in the detail viewer we are not actually saving the information but instead store them in the redux state. We are saving the resource only when we will click on save. It should be an inline editing based on the user permission in my opinion,

...I'm not even  sure if the pencil button it's really needed, probably it's more an hint that a specific section of the detail viewer is editable

**Comment by luorlandini** [comment]
@allyoucanmap @giohappy 
The buttons I meant are globally (for detail viewer) and not for a single field

**Comment by giohappy** [comment]
@allyoucanmap I admit that having "contextual saves" would probably be more clear for the user. However we must take account the context (layer, map, document) where other editing actions might be done.
I would like to improve the consistency of the save actions, that currently are quite obscure in certain cases. For example, when I change a style of a layer in Map, I need to save inside the TOC to save the status but the I also need to save the Map itself. This is a bad UX in my opinion.

Either we keep track of changes and 

1. turn the global "Save" button on when we have a dirty state
2. warn the user if there's a dirty state when he tries to to another page / resource

or we make each panel Save the resource itself whenever a save action is performed:

 - change the info -> click save in the panel -> we commit the changes to the backend
 - change a style for a layer in a map -> click the save icon -> we commit the changes
 - and so forth...
