### ISSUE TITLE
Client - Uniform items object configuration for all menus

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#94]
Currently we have four container components where we can configure menu items:
- BrandNavbar
- MenuIndex
- FilterMenu (CardsMenu)
- Footer

We should ensure that all configurations supported are the same for all this components. We would expect following initial configurations:

- link
```js
{
  "labelId": "gnhome.register",
  "type": "link",
  "href": "/account/signup/?next=/",
  "badge": "",
  "authenticated": true,
  "permissions": [],
  "allowedRoles": []
}
```
- dropdown
```js
{
  "labelId": "gnhome.register",
  "image": "",
  "type": "dropdown",
  "authenticated": true,
  "permissions": [],
  "allowedRoles": [],
  "items": []
}
```
- divider
```js
{
  "type": "divider",
  "authenticated": true,
  "permissions": [],
  "allowedRoles": [],
}
```
- filter
```js
{
  "type": "filter",
  "id": "landuse",
  "labelId": "gnhome.customFilterExample",
  "authenticated": true,
  "permissions": [],
  "allowedRoles": [],
  "query": { // query filter to use
    "filter{regions.name.in}": [
        "Global"
    ]
  }
}
```

## Variables and Expressions

It's possible to use variables in some of the value with this structure `${user.avatar}` but we should verifiy if it possible to use the same functionality we have in mapstore to have a single way to write expression in localConfig.json. (see https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/PluginsUtils.js#L171-L176).
This change could be useful taking into account that some of these component could be used as a plugin.

with handleExpression
`${user.avatar}` becomes `{state('user').avatar}`

**Important!**: all this changes must be documented in the README and in the code

**Comment by luorlandini** [comment]
about Variables and Expressions, yes, possible to use the same functionality we have in mapstore, 
we can handleExpression, instead of readProperty, for example:
this ${user.avatar} becomes {state.user.avatar}
I add this change in the PR
