### ISSUE TITLE
GeoNode API V2 - Allow request of map configuration data on the maps endpoint

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#95]
The GeoNode APIs returns the map configuration via the mapstore adpter API so to get the complete information of a map we need to perform two requests:

- adpter request `/mapstore/rest/resources/{pk}/?full=true` -> get mapstore map configuration
- API V2 request `/api/v2/maps/{pk}` -> get metadata information and permissions information of the resource

It would be nice to have a single to retrieve all the information related to map.
Could we have an endpoint similar to the one we have for geostory where adding the include[]=data param we get the app configuration?

`/api/v2/maps/{pk}?include[]=data`

**Comment by giohappy** [comment]
@mattiagiupponi let's discuss this when you get here

**Comment by mattiagiupponi** [comment]
As we saw together, this enhancement is included in this epic https://github.com/geosolutions-it/nexus-geonode/issues/106

**Comment by marthamareal** [comment]
Test passes with the following steps and output:
- Given: https://master.demo.geonode.org/api/v2/maps/1147
- Then: On checking results, `data` attribute is not returned
- GIven: https://master.demo.geonode.org/api/v2/maps/1147?include[]=data
- Then: On checking results, `data` attribute is present with map configs
